### ISSUE TITLE
[BUG] filters.filter does not apply filters that consist of a list of values

### ISSUE THREAD

**Issue by stvdrsch** [vitalik/django-ninja#1005]
**Describe the bug**
`filters.filter` that applies the defined filters does not work when applying a filter that has a list of values. If I change this filter to only accept a singular value it does work.

**Versions (please complete the following information):**
 - Python version: Python 3.11.7
 - Django version: 4.1.5
 - Django-Ninja version: 1.1.0
 - Pydantic version: 2.5.2

**Extra info**

_endpoint:_

```
@api.get("/business-units", response=List[BusinessUnitSchema])
def get_companies(request, filters: Query[IdFilterSchema]):
    """Returns all possible businessunits for this user"""
    user = get_user_from_request(request)
    return filters.filter(user.business_units.all())
```

_schema:_

```
class IdFilterSchema(FilterSchema):
    id: List[uuid.UUID] = None
```
(changing `uuid.UUID` with `str` also gives an error)

_error message:_

```
`["‘[UUID('28237095-4257-4dcc-817f-4fb322a2fa67'), UUID('cd55beb4-709b-49bf-80a9-384166f4ee55')]’ is geen geldige UUID."]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2649, in to_python
    return uuid.UUID(**{input_form: value})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/uuid.py", line 175, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
          ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/ninja/operation.py", line 107, in run
    result = self.view_func(request, **values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/expert/users/api_user/api_user.py", line 564, in get_companies
    return filters.filter(user.business_units.all())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ninja/filter_schema.py", line 53, in filter
    return queryset.filter(self.get_filter_expression())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1388, in build_filter
    return self._add_q(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2633, in get_prep_value
    return self.to_python(value)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2651, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ["‘[UUID('28237095-4257-4dcc-817f-4fb322a2fa67'), UUID('cd55beb4-709b-49bf-80a9-384166f4ee55')]’ is geen geldige UUID."`
```

**Comment by l1b3r** [comment]
By default a plain equality comparison is used to filter the dataset. What you need is this:
```python
from ninja import FilterSchema
from pydantic import Field

class IdFilterSchema(FilterSchema):
    id: List[uuid.UUID] = Field(None, q="id__in")
                                      👆
```
This will allow you to use the API in the following way:
`GET /business-units?id=uuid1&id=uuid2` -> Returns business units with id=uuid1 or uuid2

You may be interested in reading #1040 to see how filtering by OR may also be organized.

**Comment by stvdrsch** [comment]
Not a bug, was due to my lack of knowledge :)
