### ISSUE TITLE
Help figuring out what's wrong here...

### ISSUE THREAD

**Issue by DMunkei** [vitalik/django-ninja#1008]
I"m trying to represent nested objects in my model by using schemas. But I can't understand, what the issue is here. 

This is the model
```py
class Institute(models.Model):
    name = models.CharField(_("Institute"), max_length=256, unique=True)
    contact_person = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=True
    )
    faculty = models.ForeignKey(Faculty, on_delete=models.PROTECT)

    class Meta:
        verbose_name_plural = _("Institutes")
        constraints = [
            models.UniqueConstraint(fields=["name", "faculty"], name="Institute")
        ]

    def __str__(self):
        return f"{self.name} - {self.faculty}"
```
This is my Schema
```py
class FacultySchema(ModelSchema):
    contact_persons: List[UserSchema]
    class Meta:
        model = Faculty
        fields = '__all__'


class InstituteSchema(ModelSchema):
    contact_person: UserSchema
    faculty : FacultySchema
    class Meta:
        model = Institute
        #fields = '__all__'
        fields = ['name']
class TitleSchema(ModelSchema):
    name: str = None
    class Meta:
        model = Title
        fields = ['name']
        # fields = '__all__'

class UserSchema(ModelSchema):
    title: TitleSchema
    class Meta:
        model = get_user_model()
        exclude = ['id','password']
```

This is the Error I'm getting when I try to query the `Institute` Schema in the Api Docs.

```py
Traceback (most recent call last):
  File "/home/koestler/Development/oletv2/venv/lib/python3.11/site-packages/ninja/operation.py", line 108, in run
    return self._result_to_response(request, result, temporal_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koestler/Development/oletv2/venv/lib/python3.11/site-packages/ninja/operation.py", line 208, in _result_to_response
    validated_object = response_model.model_validate(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koestler/Development/oletv2/venv/lib/python3.11/site-packages/pydantic/main.py", line 503, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for NinjaResponseSchema
response.name
  Field required [type=missing, input_value=<DjangoGetter: []>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing```

I'm at my witsend here. Not sure what is wrong here...?

**Comment by vitalik** [comment]
@DMunkei something is wrong with the data you output from view function... (you passing "name" as empty list) can you show view function as well ?

**Comment by DMunkei** [comment]
This is the `api.py` Folder, I have no logic in my `views.py`
```py
@institute_router.get("/institutes/", response=InstituteSchema)
def institutes(request):
    return Institute.objects.all()
```

**Comment by DMunkei** [comment]
> @DMunkei something is wrong with the data you output from view function... (you passing "name" as empty list) can you show view function as well ?

I just updated the schema file, apologies. This is what I had in the beginning. The Traceback and Schema have been adjusted. It's having an issue with **all** of the fields on the model.

**Comment by DMunkei** [comment]
@vitalik I've figured out the issue, it was a mistake in my `api.py` file... I was typing the `response` wrong. I should have been `List[InstituteSchema]` instead of just `InstituteSchema`.
```py
@institute_router.get("/institutes/", response=List[InstituteSchema])
def institutes(request):
    return Institute.objects.all()
```
