### ISSUE TITLE
create_schema should support `BigAutoField`

### ISSUE THREAD

**Issue by rajaiswal** [vitalik/django-ninja#112]
I have a model field defined as:

```python
id = models.BigAutoField(primary_key=True)
```

`create_schema` wasn't able to handle this when I set `depth=1`. 

```python
UserSchema = create_schema(User, depth=1, fields=["uuid", "email", "first_name", "last_name", "organization"])
```

Traceback:
```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/...", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/.../schemas.py", line 82, in <module>
    UserSchema = create_schema(User, depth=1, fields=["uuid", "email", "first_name", "last_name", "organization"])
  File "/.../python3.7/site-packages/ninja/orm/factory.py", line 48, in create_schema
    python_type, field_info = get_schema_field(fld, depth=depth)
  File "/.../python3.7/site-packages/ninja/orm/fields.py", line 64, in get_schema_field
    return get_related_field_schema(field, depth=depth)
  File "/.../python3.7/site-packages/ninja/orm/fields.py", line 118, in get_related_field_schema
    schema = create_schema(model, depth=depth - 1)
  File "/.../python3.7/site-packages/ninja/orm/factory.py", line 48, in create_schema
    python_type, field_info = get_schema_field(fld, depth=depth)
  File "/.../python3.7/site-packages/ninja/orm/fields.py", line 88, in get_schema_field
    python_type = TYPES[internal_type]
KeyError: 'BigAutoField'
```
The related field's ("organization") pk was also `BigAutoField`. I quickly looked and seems like this can be resolved by just adding `"BigAutoField": int` to `ninja.orm.fields.TYPES` dict.

**Comment by vitalik** [comment]
fixed in `0.12.2`
