### ISSUE TITLE
[BUG] Pydantic 2

### ISSUE THREAD

**Issue by M3te0r** [vitalik/django-ninja#1128]
**Describe the bug**

**Versions (please complete the following information):**
 - Python version: [e.g. 3.6]
 - Django version: [e.g. 4.0]
 - Django-Ninja version: [e.g. 0.16.2]
 - Pydantic version: [e.g. 1.9.0]

Note you can quickly get this by runninng in `./manage.py shell` this line:
```
import django; import pydantic; import ninja; django.__version__; ninja.__version__; pydantic.__version__
```

**Comment by vitalik** [comment]
Hi @M3te0r 

Maybe you have specific data that you pass to validation that is failing ? Please share you Schema class and data that you are passing

the latest full test run uses pydantic2.7 did not fail at any combination - https://github.com/vitalik/django-ninja/actions/runs/8661076227

**Comment by M3te0r** [comment]
@vitalik Could reproduce with this minimal setup


```
from typing import Annotated, Literal

from ninja import Schema
from pydantic import ConfigDict
from ninja import Field

from pydantic import RootModel

class ExtraForbidSchema(Schema):
    model_config = ConfigDict(extra="forbid")

class AbstractProfileIn(ExtraForbidSchema):
    first_name: str | None = None
    last_name: str | None = None

class NewUserBOIn(ExtraForbidSchema): # <==== If Schema it's good
    email: str
    role: str
    project_id: int | None = None

class AdminProfileIn(AbstractProfileIn):
    first_name: str
    last_name: str

class AdminBOIn(NewUserBOIn):
    site_ids: list[int] | None = Field(None, json_schema_extra={"deprecated": True})
    role: Literal["ADMIN"]
    profile: AdminProfileIn

class HCProfileIn(AbstractProfileIn):
    first_name: str
    last_name: str

class HCPBOIn(NewUserBOIn):
    role: Literal["HCP"]
    project_id: int
    profile: HCProfileIn

class NewUserBOUnionIn(Schema, RootModel):
    """
    Class to discriminate between different user roles with payload
    The solution : https://github.com/pydantic/pydantic/issues/3714#issuecomment-1051093100
    """

    root: Annotated[
        (HCPBOIn | AdminBOIn),
        Field(discriminator="role"),
    ]

    def __getattr__(self, attr):
        return getattr(self.root, attr)

    def __getitem__(self, item):
        return self.root[item]


user_data = {
    "email": "test+4@exemple.com",
    "project_id": "2",
    "role": "HCP",
    "profile": {"first_name": "FOO", "last_name": "BAR"}
}


user = NewUserBOUnionIn(**user_data)
print(user.email)


```

Full traceback : 
```
Traceback (most recent call last):
  File "/home/m3te0r/PycharmProjects/bepatient-server/.venv/lib/python3.12/site-packages/ninja/schema.py", line 66, in __getattr__
    value = getattr(self._obj, key)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m3te0r/PycharmProjects/bepatient-server/.venv/lib/python3.12/site-packages/ninja/schema.py", line 62, in __getattr__
    raise AttributeError(key)
AttributeError: __dict__. Did you mean: '__dir__'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m3te0r/PycharmProjects/bepatient-server/.venv/lib/python3.12/site-packages/django/template/base.py", line 821, in __init__
    self.literal = int(var)
                   ^^^^^^^^
ValueError: invalid literal for int() with base 10: '__dict__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m3te0r/PycharmProjects/bepatient-server/.venv/lib/python3.12/site-packages/django/template/base.py", line 832, in __init__
    self.literal = mark_safe(unescape_string_literal(var))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m3te0r/PycharmProjects/bepatient-server/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 246, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/m3te0r/PycharmProjects/bepatient-server/.venv/lib/python3.12/site-packages/django/utils/text.py", line 482, in unescape_string_literal
    raise ValueError("Not a string literal: %r" % s)
ValueError: Not a string literal: '__dict__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m3te0r/PycharmProjects/bepatient-server/.venv/lib/python3.12/site-packages/ninja/schema.py", line 70, in __getattr__
    value = Variable(key).resolve(self._obj)
            ^^^^^^^^^^^^^
  File "/home/m3te0r/PycharmProjects/bepatient-server/.venv/lib/python3.12/site-packages/django/template/base.py", line 837, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Variables and attributes may not begin with underscores: '__dict__'
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.21.1/src/err/mod.rs:1098:5:
Python API call failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
--- PyO3 is resuming a panic after fetching a PanicException from Python. ---
Python stack trace below:
Traceback (most recent call last):
  File "/home/m3te0r/PycharmProjects/bepatient-server/.venv/lib/python3.12/site-packages/ninja/schema.py", line 215, in _run_root_validator
    return handler(values)
           ^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: Python API call failed
--- PyO3 is resuming a panic after fetching a PanicException from Python. ---
Python stack trace below:
Traceback (most recent call last):
  File "/home/m3te0r/PycharmProjects/bepatient-server/.venv/lib/python3.12/site-packages/ninja/schema.py", line 215, in _run_root_validator
    return handler(values)
           ^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: Python API call failed
Traceback (most recent call last):
  File "/home/m3te0r/PycharmProjects/bepatient-server/ff.py", line 70, in <module>
    user = NewUserBOUnionIn(**user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m3te0r/PycharmProjects/bepatient-server/.venv/lib/python3.12/site-packages/pydantic/root_model.py", line 71, in __init__
    self.__pydantic_validator__.validate_python(root, self_instance=self)
pyo3_runtime.PanicException: Python API call failed

```

I use combination of discriminated annotated schema + RootModel + Nested schemas with ConfigDict(extra="forbid")
If I remove the extra forbid from NewUserBOIn schema it works

**Comment by vitalik** [comment]
Hi @M3te0r 

Please check if latest pydantic (2.7.1) works for you

**Comment by M3te0r** [comment]
Hi @vitalik 
Minimal test code and actual project seems to work with pydantic v2.7.1 now
Many thanks !
