### ISSUE TITLE
[BUG] no Response object generated for ASGI api route 

### ISSUE THREAD

**Issue by brendenwest** [vitalik/django-ninja#1168]
**Describe the bug**
I'm running Django under ASGI and basic api routes are working fine. But when I follow the `django-ninja` documentation for an api route using a Schema response, I get this error:

`'QuerySet' object has no attribute 'status_code'`

requirements.txt
```
gunicorn==21.2.0
uvicorn[standard]==0.29.0
httptools==0.6.1
uvloop==0.19.0
asgiref==3.8.1

django==5.0.4
django-ninja==1.1.0
```

Route definition
```
class PersonSchema(ModelSchema):
    class Config:
        model = User
        model_fields = ["id", "username"]


@api.get("/people/", response=List[PersonSchema])
def people(request):
    return User.objects.all()
```

**Versions (please complete the following information):**
 - Python version: [3.12]
 - Django version: [4.x, 5.x]
 - Django-Ninja version: [1.1.0, 1.0, 0.22.0]
 - Pydantic version: [-na-]

Traceback
```
024-05-16 10:36:25 Traceback (most recent call last):
2024-05-16 10:36:25   File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
2024-05-16 10:36:25     raise exc_info[1]
2024-05-16 10:36:25   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
2024-05-16 10:36:25     response = await get_response(request)
2024-05-16 10:36:25                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-16 10:36:25   File "/usr/local/lib/python3.12/site-packages/django/utils/deprecation.py", line 152, in __acall__
2024-05-16 10:36:25     response = await sync_to_async(
2024-05-16 10:36:25                ^^^^^^^^^^^^^^^^^^^^
2024-05-16 10:36:25   File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
2024-05-16 10:36:25     ret = await asyncio.shield(exec_coro)
2024-05-16 10:36:25           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-16 10:36:25   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
2024-05-16 10:36:25     result = self.fn(*self.args, **self.kwargs)
2024-05-16 10:36:25              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-16 10:36:25   File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
2024-05-16 10:36:25     return func(*args, **kwargs)
2024-05-16 10:36:25            ^^^^^^^^^^^^^^^^^^^^^
2024-05-16 10:36:25   File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 107, in process_response
2024-05-16 10:36:25     if response.status_code == 404 and self.should_redirect_with_slash(request):
2024-05-16 10:36:25        ^^^^^^^^^^^^^^^^^^^^
2024-05-16 10:36:25 AttributeError: 'QuerySet' object has no attribute 'status_code'
```

Other traceback
<img width="780" alt="image" src="https://github.com/vitalik/django-ninja/assets/1683986/7ead9684-29a6-4ca0-b7dc-0d8a652d5399">

**Comment by brendenwest** [comment]
Same behavior under Hypercorn

**Comment by brendenwest** [comment]
Still an issue under v `1.3.0`

**Comment by vitalik** [comment]
Hi @brendenwest 

Could you show how you initiated  your `api` ? api = Router() ? api = NinjaAPI ? can you show more reproducible code

**Comment by brendenwest** [comment]
I've added more complete info from my views.py

**Comment by brendenwest** [comment]
Maybe related to this issue? - https://github.com/vitalik/django-ninja/issues/1277
