### ISSUE TITLE
[BUG]  mypy crashes with django-ninja installed

### ISSUE THREAD

**Issue by TranquilMarmot** [vitalik/django-ninja#1209]
**Describe the bug**

When running mypy, it crashes because of this section in `django-ninja`:

https://github.com/vitalik/django-ninja/blob/7c264e9222fc52d21032d6e2b67b1a908054c27d/ninja/conf.py#L34-L37

Output from `mypy . --show-traceback`...

```sh
/Users/me/Library/Caches/pypoetry/virtualenvs/my-project-py3.11/lib/python3.11/site-packages/ninja/conf.py:34: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.10.1
Traceback (most recent call last):
  File "mypy/checker.py", line 589, in accept
  File "mypy/nodes.py", line 1491, in accept
  File "mypy/checker.py", line 4554, in visit_if_stmt
  File "mypy/checker.py", line 5700, in find_isinstance_check
  File "mypy/checker.py", line 5739, in find_isinstance_check_helper
  File "mypy/checker.py", line 7357, in hasattr_type_maps
  File "mypy/checker.py", line 7393, in has_valid_attribute
  File "mypy/checkmember.py", line 205, in analyze_member_access
  File "mypy/checkmember.py", line 224, in _analyze_member_access
  File "mypy/checkmember.py", line 352, in analyze_instance_member_access
  File "mypy/checkmember.py", line 573, in analyze_member_var_access
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/my-project-py3.11/lib/python3.11/site-packages/mypy_django_plugin/transformers/settings.py", line 24, in get_type_of_settings_attribute
    assert isinstance(ctx.context, MemberExpr)
AssertionError: 
/Users/me/Library/Caches/pypoetry/virtualenvs/my-project-py3.11/lib/python3.11/site-packages/ninja/conf.py:34:
```

If I comment out the offending block of code, it runs fine.

**Versions (please complete the following information):**
 - Python version: 3.11.11
 - Django version: 4.1.5
 - Django-Ninja version: 1.1.0
 - Pydantic version: 2.7.4
- mypy version: 1.10.1

**Comment by TranquilMarmot** [comment]
Looks like this is because we were on an old version of `django-stubs`
