### ISSUE TITLE
[BUG] Converter `uuid` is already registered - deprecated in django 6.0

### ISSUE THREAD

**Issue by mathiasertl** [vitalik/django-ninja#1266]
**Describe the bug**

When running `python -Wd ca/manage.py check` I get a deprecation warning (paths trimmed for privacy):

```
user@host:~/src/...$ python -Wd ca/manage.py check
.../lib/python3.12/site-packages/ninja/signature/utils.py:96: RemovedInDjango60Warning: Converter 'uuid' is already registered. Support for overriding registered converters is deprecated and will be removed in Django 6.0.
  register_converter(NinjaUUIDConverter, "uuid")
```

django-ninja registers a converter called `uuid`, which is already registered by Django. Support for overriding a converter will be removed in Django 6.0. This converter is also problematic as it alters the behavior of views unrelated to django-ninja: A standard Django view using the `uuid` converter will receive a different type of value depending on if django-ninja is used or not - this was also already raised in #280.

From the looks of it, I think the converter can be safely removed. If not, it has to be renamed. Please advice on your preferred course of action, I'm happy to make a PR.

**Versions (please complete the following information):**
 - Python version: 3.12 (should not matter)
 - Django version: 5.1
 - Django-Ninja version: 1.3.0
 - Pydantic version: 2.8.2 (should not matter)

**Comment by Xdynix** [comment]
Sharing a monkeypatch I used to suppress this behavior. The behavior of the `uuid` converter has always been to return a UUID instance since Django 2.0. I don't really think it should behave differently in Django Ninja than the `int` converter (i.e. returning `str` instead of the actual type).

Add the following code to your `settings.py`.

```python
def monkeypatch_ninja_uuid_converter() -> None:
    import importlib
    import sys

    import django.urls

    module_name = "ninja.signature.utils"
    sys.modules.pop(module_name, None)

    original_register_converter = django.urls.register_converter

    def fake_register_converter(*_: Any, **__: Any) -> None:
        pass

    django.urls.register_converter = fake_register_converter
    importlib.import_module(module_name)

    django.urls.register_converter = original_register_converter


monkeypatch_ninja_uuid_converter()
```

**Comment by lapinvert** [comment]
Are we going to fix this before the release of django 6? otherwise django-ninja will stop being compatible with latest version of django.

**Comment by antoniogamizbadger** [comment]
Any update on this? :D

**Comment by ncrozz** [comment]
I have problems also with the workaround by @Xdynix, Django can't start at the moment exiting with Pydantic warning.
Actually I'm starting a new project with static typing setup (mypy and django-stubs) and I think it's related to this.

```
Traceback (most recent call last):
...
File "/code/server/settings/__init__.py", line 23, in <module>
  monkeypatch_ninja_uuid_converter()
File "/code/utils/ninjafix.py", line 21, in monkeypatch_ninja_uuid_converter
  importlib.import_module(module_name)
...
File "/usr/local/lib/python3.12/site-packages/ninja/__init__.py", line 9, in <module>
  from ninja.filter_schema import FilterSchema
File "/usr/local/lib/python3.12/site-packages/ninja/filter_schema.py", line 8, in <module>
  from .schema import Schema
File "/usr/local/lib/python3.12/site-packages/ninja/schema.py", line 209, in <module>
  class Schema(BaseModel, metaclass=ResolverMetaclass):
File "/usr/local/lib/python3.12/site-packages/ninja/schema.py", line 181, in __new__
  result = super().__new__(cls, name, bases, namespace, **kwargs)
...
    warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
pydantic.warnings.PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
```

Versions:
- Python version: 3.12.7
- Django version: 5.1
- Django-Ninja version: 1.3.0

**Comment by Xdynix** [comment]
@ncrozz This is #1245. And it's just a warning and shouldn't prevent the code from execution.

**Comment by bulldogukbcm** [comment]
My issue #1452 was closed and refers here - I agree that a warning "should" not prevent running, but in my case, it is causing my pytest suite to fail.  There was a suggestion that this converter could be removed as it's not doing anything?  I'm not familiar with your code base yet, but happy to raise a PR if you need more fingers on keys.

**Comment by vitalik** [comment]
@bulldogukbcm the fix already in "main" branch - you cant test agains it

**Comment by vitalik** [comment]
fixed in 1.4.2
