### ISSUE TITLE
`JSONField` should not be mapping to pydantic `Json`

### ISSUE THREAD

**Issue by MisLink** [vitalik/django-ninja#127]
django will decode that field to a python object.

**Comment by nabnux** [comment]
Hello,

To add more details to this issue I think I bumped into the same problem after using `create_schema` on a model with a `JSONField` and trying to use it as a reponse model in an endpoint:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ninja/operation.py", line 94, in run
    return self._result_to_response(request, result)
  File "/usr/local/lib/python3.9/site-packages/ninja/operation.py", line 177, in _result_to_response
    result = response_model.from_orm(resp_object).dict(
  File "pydantic/main.py", line 573, in pydantic.main.BaseModel.from_orm
pydantic.error_wrappers.ValidationError: 1 validation error for NinjaResponseSchema
response -> variants
  JSON object must be str, bytes or bytearray (type=type_error.json)
```
