### ISSUE TITLE
How I can to use resolve_<field> for async api?

### ISSUE THREAD

**Issue by BRANYA43** [vitalik/django-ninja#1277]
When I tested my API to get the country list I got a following `error` when `pydantic` tried to serialize a `info` field asynchronously:
```console
Traceback (most recent call last):
  File "/home/branya/Документи/My Projects/Django/guide_self_api/.venv/lib/python3.11/site-packages/asgiref/sync.py", line 254, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/branya/Документи/My Projects/Django/guide_self_api/.venv/lib/python3.11/site-packages/asgiref/sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/branya/Документи/My Projects/Django/guide_self_api/src/travels/tests/test_api.py", line 43, in test_api_returns_country_list_data
    response = await self.client.get('/countries', headers={'Accept-Language': 'en'})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/branya/Документи/My Projects/Django/guide_self_api/.venv/lib/python3.11/site-packages/ninja/testing/client.py", line 169, in _call
    return NinjaResponse(await func(request, **kwargs))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/branya/Документи/My Projects/Django/guide_self_api/.venv/lib/python3.11/site-packages/ninja/operation.py", line 473, in _async_view
    return await cast(AsyncOperation, operation).run(request, *a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/branya/Документи/My Projects/Django/guide_self_api/.venv/lib/python3.11/site-packages/ninja/operation.py", line 336, in run
    return self.api.on_exception(request, e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/branya/Документи/My Projects/Django/guide_self_api/.venv/lib/python3.11/site-packages/ninja/main.py", line 515, in on_exception
    return handler(request, exc)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/branya/Документи/My Projects/Django/guide_self_api/.venv/lib/python3.11/site-packages/ninja/errors.py", line 114, in _default_exception
    raise exc  # let django deal with it
    ^^^^^^^^^
  File "/home/branya/Документи/My Projects/Django/guide_self_api/.venv/lib/python3.11/site-packages/ninja/operation.py", line 334, in run
    return self._result_to_response(request, result, temporal_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/branya/Документи/My Projects/Django/guide_self_api/.venv/lib/python3.11/site-packages/ninja/operation.py", line 260, in _result_to_response
    validated_object = response_model.model_validate(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/branya/Документи/My Projects/Django/guide_self_api/.venv/lib/python3.11/site-packages/pydantic/main.py", line 568, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 6 validation errors for NinjaResponseSchema
response.0.info
  Error extracting attribute: SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async. [type=get_attribute_error, input_value=<DjangoGetter: <Country: england>>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.8/v/get_attribute_error

```

It's happening with the following code.
```python
# Models
class Country(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid4,
        db_index=True,
        editable=False,
    )
    info = GenericRelation(
        verbose_name='Localized Information',
        to='Info',
    )

class Info(models.Model):
    slug = models.SlugField()
    name = models.CharField(
        max_length=100,
        validators=[MinLengthValidator(2)],
    )
    short_descr = models.TextField(
        null=True, 
        blank=True, 
        validators=[MaxLengthValidator(2048)],
    )
    content_type = models.ForeignKey(
        to=ContentType,
        on_delete=models.PROTECT,
    )
    object_id = models.UUIDField()
    content_obj = GenericForeignKey()

# Schemas
class InfoSummaryField(ModelSchema):
    class Meta:
        model = Info
        fields = ('name', 'short_descr')
        
class CountrySummarySchema(ModelSchema):
    id: UUID4
    info: InfoSummaryField | None
    @staticmethod
    def resolve_info(obj) -> Info | None:
        return obj.info.first()

    class Meta:
        model = Country
        fields = ('id', 'info')


# API Rout
@router.get('/countries', response=list[CountrySummarySchema])
async def get_country_list(request):
    countries = await sync_to_async(list)(Country.objects.prefetch_related('info'))
    return countries
```

I tried to use `async\await` in the `resolve_info` method, but `pydantic` cannot work asynchronously. I'm beginner in the asynchronous, so I could miss or don't know some thing to solve this issue.

Please help me. Thank you for your help earlier

**Comment by gino-sendmarc** [comment]
@BRANYA43 Have you managed to get a fix for this? I'm currently stuck on it

**Comment by BRANYA43** [comment]
[gino-sendmarc](https://github.com/gino-sendmarc) No. Pydantic work only synchronously. So I used my solution from that post.
You can use `.value()` in `get_country_list_with_info_and_main_image `and you don't need to use `serialize_country_data`

**Comment by murrple-1** [comment]
Another possibility, if it works for your usecase, is to use `QuerySet.annotate()` to 'inject' the objects with the field ahead-of-time (prior to Pydantic's ingestion and serialization)

**Comment by gino-sendmarc** [comment]
@BRANYA43 Thanks. That really sucks. 20 second code now is gonna take way longer. I will try that

**Comment by ryanovas** [comment]
Is there any progress on this? This is a massive blocker for a framework that heavily advertises its async support...

**Comment by fernandosmither** [comment]
any updates?

<img width="226" height="223" alt="Image" src="https://github.com/user-attachments/assets/d41f08d9-1688-4645-a075-bd3b5d4f6e5a" />

**Comment by vitalik** [comment]
@fernandosmither - well looks like pydantic does not allows us to have some async hook in there 

also that seesm too complex - imagine you have class that have sync and async resolvers - that becomes a nightmare to resolve

**Comment by ryanovas** [comment]
@vitalik isn't that literally what Django does right now with the models? You have save and asave for example. 

There could also just be an async version of the class that assumes async.
