### ISSUE TITLE
create_schema: ValueError: cannot specify both default and default_factory

### ISSUE THREAD

**Issue by rg3915** [vitalik/django-ninja#135]
Hi,
i have this error, after clone my repo and run `python manage.py migrate`
```
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/me/.pyenv/versions/3.8.9/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/me/.pyenv/versions/3.8.9/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/me/myproject/.venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/me/myproject/.venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/me/myproject/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/home/me/myproject/.venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/me/myproject/.venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/me/myproject/.venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/me/myproject/.venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "/home/me/myproject/.venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/me/myproject/.venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/me/myproject/.venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/me/myproject/.venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/me/.pyenv/versions/3.8.9/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/me/myproject/backend/urls.py", line 4, in <module>
    from .api import api
  File "/home/me/myproject/backend/api.py", line 3, in <module>
    from backend.product.api import router as product_router
  File "/home/me/myproject/backend/product/api.py", line 11, in <module>
    ProductSchema = create_schema(Product)
  File "/home/me/myproject/.venv/lib/python3.8/site-packages/ninja/orm/factory.py", line 57, in create_schema
    create_pydantic_model(name, __base__=Schema, **definitions),  # type: ignore
  File "pydantic/main.py", line 990, in pydantic.main.create_model
  File "pydantic/main.py", line 299, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 403, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 388, in pydantic.fields.ModelField._get_field_info
  File "pydantic/fields.py", line 173, in pydantic.fields.FieldInfo._validate
ValueError: cannot specify both default and default_factory
```

**Comment by vitalik** [comment]
Hi @rg3915 

Can you provide code example you use for create_schema ?

**Comment by rg3915** [comment]
@vitalik This was the code before the change. [b9f15737](https://github.com/rg3915/automation-team-store-challenge/commit/b9f15737cfa48ebdd8db5bbe2936ba01dbe0e9ae#diff-82e0565570447a615d6243e6e633903c8ca9275608a0f953eb644b454cc1d3b1L11)

**Comment by rngallen** [comment]
Faced the same problem when I want to create schema for User model  
`UserOut = create_schema(User,depth=1, exclude=["password", 'is_superuser', 'is_staff'])`

**Comment by vitalik** [comment]
fixed in 0.13.0

**Comment by rngallen** [comment]
Thanks what if I would to override some fields related to foreign key
 `UserOut = create_schema(User,depth=1, exclude=["password", 'is_superuser', 'is_staff'])` 
related models are groups and permissions now how can I modify which field to be displayed from linked models?
![image](https://user-images.githubusercontent.com/47332486/118661645-fdee7380-b7f7-11eb-95c3-e841a71d1d39.png)

**Comment by rngallen** [comment]
> 
> 
> Thanks what if I would to override some fields related to foreign key
> `UserOut = create_schema(User,depth=1, exclude=["password", 'is_superuser', 'is_staff'])`
> related models are groups and permissions now how can I modify which field to be displayed from linked models?
> ![image](https://user-images.githubusercontent.com/47332486/118661645-fdee7380-b7f7-11eb-95c3-e841a71d1d39.png)

Currently am using this option
![image](https://user-images.githubusercontent.com/47332486/118661869-32622f80-b7f8-11eb-8d79-fd92262fc4d6.png)
need to know if `create_schema` can accommodate this

**Comment by vitalik** [comment]
@rg3915 

try the following:

```Python
GroupSchema = create_schema(Group, fields=['id', 'name'])

UserSchema = create_schema(User, custom_fields=[
     ('groups', List[GroupSchema], None),
])
```

**Comment by vitalik** [comment]
note: custom_fields added in 0.13

**Comment by rg3915** [comment]
> @rg3915
> 
> try the following:
> 
> ```python
> GroupSchema = create_schema(Group, fields=['id', 'name'])
> 
> UserSchema = create_schema(User, custom_fields=[
>      ('groups', List[GroupSchema], None),
> ])
> ```

It worked out. Thank you @vitalik
