### ISSUE TITLE
async queryset for many to many field?

### ISSUE THREAD

**Issue by frocelu** [vitalik/django-ninja#177]
I like this project very much! Great work!
And now I am learning to use it.

This is my models.py
```Python
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=20)


class Book(models.Model):
    name = models.CharField(max_length=20)
    author = models.ManyToManyField("Author")
```

api.py
```Python
from ninja import Router
from .models import *
from asgiref.sync import sync_to_async
from .schemas import *
from typing import List

router = Router()


@sync_to_async
def to_list(q):
    return list(q)


@router.get('/books', response=List[BookSchema])
async def r_books(request):
    books = await to_list(Book.objects.all)
    return books


@router.get('/authors', response=List[AuthorSchema])
async def r_authors(request):
    authors = await to_list(Author.objects.all())
    return authors
```

schemas.py
```Python
from ninja.orm import create_schema
from django.contrib.auth.models import User
from .models import *

UserSchema = create_schema(User, fields=['id', 'username'])
BookSchema = create_schema(Book, depth=1)
AuthorSchema = create_schema(Author)
```

When I use the route "/api/books", I get an error 「django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.」
```
You cannot call this from an async context - use a thread or sync_to_async.
Traceback (most recent call last):
  File "C:\Users\froce\Desktop\新增資料夾 (4)\VENV\lib\site-packages\ninja\operation.py", line 232, in run
    return self._result_to_response(request, result)
  File "C:\Users\froce\Desktop\新增資料夾 (4)\VENV\lib\site-packages\ninja\operation.py", line 177, in _result_to_response
    result = response_model.from_orm(resp_object).dict(
  File "pydantic\main.py", line 629, in pydantic.main.BaseModel.from_orm
  File "pydantic\main.py", line 1040, in pydantic.main.validate_model
  File "pydantic\fields.py", line 734, in pydantic.fields.ModelField.validate
  File "pydantic\fields.py", line 767, in pydantic.fields.ModelField._validate_sequence_like
  File "pydantic\fields.py", line 899, in pydantic.fields.ModelField._validate_singleton
  File "pydantic\fields.py", line 723, in pydantic.fields.ModelField.validate
  File "pydantic\fields.py", line 906, in pydantic.fields.ModelField._validate_singleton
  File "pydantic\fields.py", line 913, in pydantic.fields.ModelField._apply_validators
  File "pydantic\class_validators.py", line 310, in pydantic.class_validators._generic_validator_basic.lambda12
  File "pydantic\main.py", line 737, in pydantic.main.BaseModel.validate
  File "pydantic\main.py", line 629, in pydantic.main.BaseModel.from_orm
  File "pydantic\main.py", line 1019, in pydantic.main.validate_model
  File "C:\Users\froce\Desktop\新增資料夾 (4)\VENV\lib\site-packages\ninja\schema.py", line 25, in get
    return list(result.all())
  File "C:\Users\froce\Desktop\新增資料夾 (4)\VENV\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\Users\froce\Desktop\新增資料夾 (4)\VENV\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\froce\Desktop\新增資料夾 (4)\VENV\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\froce\Desktop\新增資料夾 (4)\VENV\lib\site-packages\django\db\models\sql\compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "C:\Users\froce\Desktop\新增資料夾 (4)\VENV\lib\site-packages\django\utils\asyncio.py", line 24, in inner
    raise SynchronousOnlyOperation(message)
django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
```

**Comment by vitalik** [comment]
hi @frocelu 

yes, if you want to output related objects in async mode - you need to do it in one database query (with select_related or prefetch related)


```Python

@router.get('/books', response=List[BookSchema])
async def r_books(request):
    qs = Book.objects.prefetch_related('author')  # ! <-------------
    books = await to_list(qs)
    return books

```

**Comment by frocelu** [comment]
> 
> 
> hi @frocelu
> 
> yes, if you want to output related objects in async mode - you need to do it in one database query (with select_related or prefetch related)
> 
> ```python
> @router.get('/books', response=List[BookSchema])
> async def r_books(request):
>     qs = Book.objects.prefetch_related('author')  # ! <-------------
>     books = await to_list(qs)
>     return books
> ```

Oh, seems I forgot it. I will try it.
