### ISSUE TITLE
How can I catch django.core.exceptions.PermissionDenied 

### ISSUE THREAD

**Issue by rngallen** [vitalik/django-ninja#182]
How can I catch `django.core.exceptions.PermissionDenied `on django ninja?
```django.contrib.auth.decorators import permission_required 

@transaction.atomic
@permission_required("users.add_customuser", raise_exception=True)
def create_user(request, payload: UserCreateSchema):
      ...
```
```
Traceback (most recent call last):
  File "C:\Users\luqman\.virtualenvs\fuel_delivery-yohdrzeD\lib\site-packages\ninja\operation.py", line 93, in run
    result = self.view_func(request, **values)
  File "c:\python39\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Users\luqman\.virtualenvs\fuel_delivery-yohdrzeD\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    if test_func(request.user):
  File "C:\Users\luqman\.virtualenvs\fuel_delivery-yohdrzeD\lib\site-packages\django\contrib\auth\decorators.py", line 71, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied <========####????
ERROR Internal Server Error: /api/users
ERROR "POST /api/users HTTP/1.1" 500 663
```

**Comment by vitalik** [comment]
Hi @rngallen 

Try https://django-ninja.rest-framework.com/tutorial/errors/#custom-exception-handlers

```Python
@api.exception_handler(PermissionDenied)
def perm_denied_exception(request, exc):
    return api.create_response(
        request,
        {"message": "Permission Denied"},
        status=403,
    )

```
