### ISSUE TITLE
API documentation generation for schema with nested "create_schema" fails

### ISSUE THREAD

**Issue by Alex-Sichkar** [vitalik/django-ninja#214]
The following schema:
```python
class BlogSchema(Schema):
    id: int
    slug: str
    posts: list[
        create_schema(
            BlogPost,
            fields=['id', 'contents'],
            custom_fields=[('author', create_schema(User, fields=['id', 'full_name']), ...)],
        )
    ]
```
fails with:
```python
Internal Server Error: /api/openapi.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/ninja/openapi/views.py", line 25, in openapi_json
    schema = api.get_openapi_schema()
  File "/usr/local/lib/python3.9/site-packages/ninja/main.py", line 338, in get_openapi_schema
    return get_schema(api=self, path_prefix=path_prefix)
  File "/usr/local/lib/python3.9/site-packages/ninja/openapi/schema.py", line 21, in get_schema
    openapi = OpenAPISchema(api, path_prefix)
  File "/usr/local/lib/python3.9/site-packages/ninja/openapi/schema.py", line 43, in __init__
    ("paths", self.get_paths()),
  File "/usr/local/lib/python3.9/site-packages/ninja/openapi/schema.py", line 55, in get_paths
    path_methods = self.methods(path_view.operations)
  File "/usr/local/lib/python3.9/site-packages/ninja/openapi/schema.py", line 66, in methods
    result[method.lower()] = self.operation_details(op)
  File "/usr/local/lib/python3.9/site-packages/ninja/openapi/schema.py", line 80, in operation_details
    "responses": self.responses(operation),
  File "/usr/local/lib/python3.9/site-packages/ninja/openapi/schema.py", line 185, in responses
    schema, _ = self._create_schema_from_model(model, by_alias=False)
  File "/usr/local/lib/python3.9/site-packages/ninja/openapi/schema.py", line 134, in _create_schema_from_model
    schema = model_schema(model, ref_prefix=REF_PREFIX, by_alias=by_alias)
  File "pydantic/schema.py", line 167, in pydantic.schema.model_schema
  File "pydantic/schema.py", line 548, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 589, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 241, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 495, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 842, in pydantic.schema.field_singleton_schema
  File "pydantic/schema.py", line 548, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 589, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 241, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 440, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 773, in pydantic.schema.field_singleton_schema
  File "pydantic/schema.py", line 667, in pydantic.schema.field_singleton_sub_fields_schema
  File "pydantic/schema.py", line 495, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 842, in pydantic.schema.field_singleton_schema
  File "pydantic/schema.py", line 548, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 589, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 241, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 440, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 773, in pydantic.schema.field_singleton_schema
  File "pydantic/schema.py", line 667, in pydantic.schema.field_singleton_sub_fields_schema
  File "pydantic/schema.py", line 495, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 842, in pydantic.schema.field_singleton_schema
  File "pydantic/schema.py", line 548, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 589, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 241, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 495, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 840, in pydantic.schema.field_singleton_schema
KeyError: <class 'pydantic.main.Author'>
```

**Comment by stephenrauch** [comment]
It would be easier to help if you included all the code needed to duplicate the error seen.  I coded the following test attempting to replicate the provided snippet with some presumptions about the not included models.  But the test below passes.

```python
def test_nested_create():
    from django.db import models
    from ninja import NinjaAPI, Schema
    from ninja.orm import create_schema

    class Related(models.Model):
        charfield = models.CharField()

        class Meta:
            app_label = "tests"

    class TestModel(models.Model):
        charfield = models.CharField()
        related = models.ForeignKey(Related, on_delete=models.SET_NULL, null=True)

        class Meta:
            app_label = "tests"

    class TestSchema(Schema):
        id: int
        data: list[
            create_schema(
                TestModel,
                fields=['id', 'charfield'],
                custom_fields=[('related', create_schema(Related, fields=['id', 'charfield']), ...)],
            )
        ]

    api = NinjaAPI()

    @api.get("/test", response=TestSchema)
    def test_method(request):
        return []

    assert api.get_openapi_schema()['components'] == {
        'schemas': {
            'Related': {
                'properties': {
                    'charfield': {'title': 'Charfield', 'type': 'string'},
                    'id': {'title': 'Id', 'type': 'integer'}
                },
                'required': ['charfield'],
                'title': 'Related',
                'type': 'object'
            },
            'TestModel': {
                'properties': {
                    'charfield': {'title': 'Charfield', 'type': 'string'},
                    'id': {'title': 'Id', 'type': 'integer'},
                    'related': {'$ref': '#/components/schemas/Related'}
                },
                'required': ['charfield', 'related'],
                'title': 'TestModel',
                'type': 'object'
            },
            'TestSchema': {
                'properties': {
                    'id': {'title': 'Id', 'type': 'integer'},
                    'data': {
                        'items': {'$ref': '#/components/schemas/TestModel'},
                        'title': 'Data',
                        'type': 'array'
                    },
                },
                'required': ['id', 'data'],
                'title': 'TestSchema',
                'type': 'object'
            }
        }
    }
```

**Comment by Alex-Sichkar** [comment]
@stephenrauch i created minimal project that reproduces the issue
[django-ninja-issue-214.zip](https://github.com/vitalik/django-ninja/files/7096857/django-ninja-issue-214.zip)

**Comment by stephenrauch** [comment]
Your original report did not show that you are using `create_schema` on the same model but with different values.  Using the same Model  but with different configurations seems to makes pydantic angry.  You are going to need to either use only 1 User schema or give your created schemas different names.
