### ISSUE TITLE
Fail to catch exception on transaction.atomic

### ISSUE THREAD

**Issue by rngallen** [vitalik/django-ninja#219]
I want to catch exception on try...except,
This code below works perfect and managed to catch exception 
```
@router.post("/deliveryRequests", response={201: Message, 400: Message}, tags=["deliveryRequests"])
def create_delivery_request(request, payload: DeliveryRequestInSchema):
    """Created PipeLine Delivery Request"""
    data = payload.dict()
    data["created_by"] = request.user
    try:
        delivery_request = DeliveryRequest.objects.create(**data)
    except IntegrityError as e:
        error_msg = clean_error_message(e)
        return HTTPStatus.BAD_REQUEST, {"detail": [{"msg": error_msg}]}
    return HTTPStatus.CREATED, {
        "detail": [{"msg": f"Delivery request created successfully", "id": delivery_request.id}]
    }
```

but when I want to run this code on atomic like this 

```
@router.post("/deliveryRequests", response={201: Message, 400: Message}, tags=["deliveryRequests"])
@transaction.atomic  #<--------------------- ATOMIC ####
def create_delivery_request(request, payload: DeliveryRequestInSchema):
    """Created PipeLine Delivery Request"""
    data = payload.dict()
    data["created_by"] = request.user
    try:
        with transaction.atomic(): #<--------------------- ATOMIC ####
            delivery_request = DeliveryRequest.objects.create(**data)
    except IntegrityError as e:
        error_msg = clean_error_message(e)
        return HTTPStatus.BAD_REQUEST, {"detail": [{"msg": error_msg}]}
    return HTTPStatus.CREATED, {
        "detail": [{"msg": f"Delivery request created successfully", "id": delivery_request.id}]
    }
```

 It fails to catch exception from foreign key constraint . where am I doing it wrong?
schem
```
class DeliveryRequestInSchema(Schema):
    description: str = Field(..., max_length=120)
    request_date: date
    vessel_date: date
    customer_id: int
    customer_name: str = Field(..., max_length=60)
    customer_loading_order: bool = False
    valid_contract_available: bool = False
    product_id: int
    product_no: str = Field(..., max_length=24)
    product_description: str = Field(..., max_length=60)
    product_category: str = Field(..., max_length=6)
    vessel_id: int
    vessel_description: str = Field(..., max_length=60)
    quantity: condecimal(ge=1000, max_digits=15, decimal_places=2)
    metric_tones: condecimal(gt=0, max_digits=15, decimal_places=2)
    vessel_density: condecimal(gt=0, max_digits=15, decimal_places=8)

    class Config(Schema.Config):
        anystr_strip_whitespace = True
        alias_generator = to_camel
```
response

```
Traceback (most recent call last):
  File "C:\Users\luqman\.virtualenvs\fuel_delivery-yohdrzeD\lib\site-packages\django\db\backends\base\base.py", line 242, in _commit
    return self.connection.commit()
psycopg2.errors.ForeignKeyViolation: insert or update on table "PIPELINE.DELIVERY.REQUEST" violates foreign key constraint "PIPELINE.DELIVERY.RE_customer_id_09ddb92d_fk_SAGE.CUST"
DETAIL:  Key (customer_id)=(110) is not present in table "SAGE.CUSTOMER".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\luqman\.virtualenvs\fuel_delivery-yohdrzeD\lib\site-packages\ninja\operation.py", line 94, in run
    result = self.view_func(request, **values)
  File "c:\python39\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Users\luqman\.virtualenvs\fuel_delivery-yohdrzeD\lib\site-packages\django\db\transaction.py", line 246, in __exit__
    connection.commit()
  File "C:\Users\luqman\.virtualenvs\fuel_delivery-yohdrzeD\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\luqman\.virtualenvs\fuel_delivery-yohdrzeD\lib\site-packages\django\db\backends\base\base.py", line 266, in commit
    self._commit()
  File "C:\Users\luqman\.virtualenvs\fuel_delivery-yohdrzeD\lib\site-packages\django\db\backends\base\base.py", line 242, in _commit
    return self.connection.commit()
  File "C:\Users\luqman\.virtualenvs\fuel_delivery-yohdrzeD\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\luqman\.virtualenvs\fuel_delivery-yohdrzeD\lib\site-packages\django\db\backends\base\base.py", line 242, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: insert or update on table "PIPELINE.DELIVERY.REQUEST" violates foreign key constraint "PIPELINE.DELIVERY.RE_customer_id_09ddb92d_fk_SAGE.CUST"
DETAIL:  Key (customer_id)=(110) is not present in table "SAGE.CUSTOMER".
```

**Comment by stephenrauch** [comment]
From the [docs](https://docs.djangoproject.com/en/3.2/topics/db/transactions/#django.db.transaction.atomic):

> `atomic()` is usable both as a [decorator](https://docs.python.org/3/glossary.html#term-decorator) and as a [context manager](https://docs.python.org/3/glossary.html#term-context-manager)...

You are using it as both.  Looking at your code I would suggest starting by removing the `atomic` decorator.

**Comment by rngallen** [comment]
Hahahah for sure. Thanks
