### ISSUE TITLE
Install  NinjaAPI in app not global : 'openapi-json' is not a valid view function  And view function missing 1 required positional argument

### ISSUE THREAD

**Issue by jiamo** [vitalik/django-ninja#220]
With `NinjaAPI` install in app path and `uvicorn`. The doc url got such error:

```
handing  127.0.0.1
...hello process_exception Traceback (most recent call last):
  File "/Users/jiamo/.pyenv/versions/3.9.1/envs/cms/lib/python3.9/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/Users/jiamo/.pyenv/versions/3.9.1/envs/cms/lib/python3.9/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiamo/.pyenv/versions/3.9.1/envs/cms/lib/python3.9/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/Users/jiamo/.pyenv/versions/3.9.1/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/Users/jiamo/.pyenv/versions/3.9.1/envs/cms/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/jiamo/.pyenv/versions/3.9.1/envs/cms/lib/python3.9/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/Users/jiamo/.pyenv/versions/3.9.1/envs/cms/lib/python3.9/site-packages/ninja/openapi/views.py", line 37, in swagger
    "openapi_json_url": reverse(f"{api.urls_namespace}:openapi-json"),
  File "/Users/jiamo/.pyenv/versions/3.9.1/envs/cms/lib/python3.9/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/jiamo/.pyenv/versions/3.9.1/envs/cms/lib/python3.9/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'openapi-json' not found. 'openapi-json' is not a valid view function or pattern name.
```

But when install  `NinjaAPI` in global . There is no such error.

**Comment by jiamo** [comment]
I think this is related to https://github.com/vitalik/django-ninja/issues/216

**Comment by vitalik** [comment]
@jiamo 

well it's really hard to tell what's the issue..
if you can isolate some code example into some zip file ?

**Comment by jiamo** [comment]
https://github.com/jiamo/ninja_test
` python manage.py runserver` and  chrome access `http://127.0.0.1:8000/ninja_app/docs/`

**Comment by pvyParts** [comment]
I overcame this in a small app I've been working on by changing the api's `urls_namespace` to include the `namespace` that the app is included with in the global url file, in your test apps case.

https://github.com/jiamo/ninja_test/blob/main/ninja_test/ninja_app/urls.py#L5
```python
api = NinjaAPI(urls_namespace="ninja_app:api", docs_url="/docs/")
 ```

tested with your repo, updated as above and i get the docs screen as expected.

**Comment by jiamo** [comment]
thanks. it works
