### ISSUE TITLE
Return schema from query database

### ISSUE THREAD

**Issue by JFeldaca** [vitalik/django-ninja#409]
Hi! I recently discover this package and I'm in love with it, it is an awesome work you done, all of you.

But, I want to return an Schema from the result of a query to the ddbb, and I don't get it how it can be done, Can you please leave me a hint or a hand?

schemas.py
```
class TicketHistorySchemaOut(Schema):
    purchase_id: int
    offer_name: str
    price: int
    offer_duration: int
```

api.py
```
class GlobalAuth(HttpBearer):
    def authenticate(self, request, token):
        env_tk = env.str('API_TOKEN', default='rAIGCokgCIKBXNeWwYVzGFbEqTwFMsQG')
        if token == env_tk:
            return token

        with connection.cursor() as cursor:
            cursor.execute(f"SELECT `key` FROM authtoken_token WHERE `key` = '{token}'")
            result = cursor.fetchone()
            if result is not None:
                return token

api = NinjaAPI(
    version="1.0.0",
    auth=GlobalAuth()
)

@api.get('/consumption/ticket-services/history/{language}/{payment_object_id}/')
def get_history(request, language: str, payment_object_id: int):
    with connection.cursor() as cursor:
        query = f"""
            SELECT
                op.purchase_id,
                CASE WHEN ol.name IS NULL
                THEN o.name
                ELSE ol.name END as offer_name,
                o.price,
                CASE WHEN o.running_time = 0
                THEN date_add(op.date, INTERVAL o.duration MINUTE)
                ELSE o.duration END as offer_duration
            FROM offer_purchases op
            INNER JOIN offers o ON op.offer_id = o.offer_id
            LEFT JOIN offer_localizations ol ON o.offer_id = ol.offer_id AND ol.languages_id = '{language}'
            INNER JOIN payment_objects p ON op.payment_object_id = p.id AND p.id = {payment_object_id}
        """

        cursor.execute(query)
        response = []
        row = cursor.fetchall()
        for data in row:
            response.append({
                "purchase_id": data[0],
                "offer_name": data[1],
                "price": data[2],
                "offer_duration": data[3]
            })
        cursor.close()
    return response
```

As you can see, I build the object to return, but I would prefered return a colection of  schemas in an array, similar to this:

```
[
 {
    Schema
 },
 {
    Schema
 },
 ...
]
```

**Comment by vitalik** [comment]
Hi @JFeldaca 

django-ninja is built on top of pydantic library

what you can do is use pydantic's dataclass - that allows you to pass argumennts as args instead of **k**wargs:

```Python
from pydantic.dataclasses import dataclass

@dataclass
class TicketHistorySchemaOut:
     purchase_id: int
     offer_name: str
     price: int
     offer_duration: int
 
...

rows = cursor.fetchall()
items = [TicketHistorySchemaOut(*i) for i in rows]


```

**Comment by JFeldaca** [comment]
Hi @vitalik !

Thanks for the response, but it didn't work.

When I hit the endpoint, the response is a 500.

Response from api
```
HTTP/1.1 500 Internal Server Error
Date: Tue, 29 Mar 2022 06:27:19 GMT
Server: WSGIServer/0.2 CPython/3.8.10
Content-Type: text/plain
X-Frame-Options: DENY
Content-Length: 649
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Cross-Origin-Opener-Policy: same-origin

Traceback (most recent call last):
  File "/home/dcarnicer/workspace/projects/medip-api/.venv/lib/python3.8/site-packages/ninja/operation.py", line 99, in run
    result = self.view_func(request, **values)
  File "/home/dcarnicer/workspace/projects/medip-api/api/api.py", line 860, in get_history
    response = [TicketHistorySchemaOut(*i) for i in rows]
  File "/home/dcarnicer/workspace/projects/medip-api/api/api.py", line 860, in <listcomp>
  File "<string>", line 3, in __init__
  File "pydantic/main.py", line 391, in pydantic.main.BaseModel.__setattr__
AttributeError: __fields_set__
```
api.py
```
@api.get('/consumption/ticket-services/history/{language}/{payment_object_id}/')
def get_history(request, language: str, payment_object_id: int):
    with connection.cursor() as cursor:
        query = f"""
            SELECT
                op.purchase_id,
                CASE WHEN ol.name IS NULL
                THEN o.name
                ELSE ol.name END as offer_name,
                o.price as price,
                CASE WHEN o.running_time = 0
                THEN date_add(op.date, INTERVAL o.duration MINUTE)
                ELSE o.duration END as offer_duration
            FROM offer_purchases op
            INNER JOIN offers o ON op.offer_id = o.offer_id
            LEFT JOIN offer_localizations ol ON o.offer_id = ol.offer_id AND ol.languages_id = '{language}'
            INNER JOIN payment_objects p ON op.payment_object_id = p.id AND p.id = {payment_object_id}
        """

        cursor.execute(query)
        rows = cursor.fetchall()
        response = [TicketHistorySchemaOut(*i) for i in rows]
        cursor.close()
    return response
```
schemas.py
```
from pydantic.dataclasses import dataclass

@dataclass
class TicketHistorySchemaOut(Schema):
    purchase_id: int
    offer_name: str
    price: int
    offer_duration: int
```

**Comment by vitalik** [comment]
@JFeldaca 

Keep attention on class inheritance - do not inherit it from Schema if you use dataclass
```Python
# NOT:
@dataclass
class TicketHistorySchemaOut(Schema):
   ...

#BUT:
@dataclass
class TicketHistorySchemaOut:
   ...

**Comment by JFeldaca** [comment]
@vitalik Thanks for the response, but, it didn't work:

Response from api:
```
HTTP/1.1 500 Internal Server Error
Date: Tue, 29 Mar 2022 08:28:37 GMT
Server: WSGIServer/0.2 CPython/3.8.10
Content-Type: text/plain
X-Frame-Options: DENY
Content-Length: 1657
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Cross-Origin-Opener-Policy: same-origin

Traceback (most recent call last):
  File "/home/dcarnicer/workspace/projects/medip-api/.venv/lib/python3.8/site-packages/ninja/operation.py", line 100, in run
    return self._result_to_response(request, result)
  File "/home/dcarnicer/workspace/projects/medip-api/.venv/lib/python3.8/site-packages/ninja/operation.py", line 184, in _result_to_response
    return self.api.create_response(request, result, status=status)
  File "/home/dcarnicer/workspace/projects/medip-api/.venv/lib/python3.8/site-packages/ninja/main.py", line 341, in create_response
    content = self.renderer.render(request, data, response_status=status)
  File "/home/dcarnicer/workspace/projects/medip-api/.venv/lib/python3.8/site-packages/ninja/renderers.py", line 25, in render
    return json.dumps(data, cls=self.encoder_class, **self.json_dumps_params)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/dcarnicer/workspace/projects/medip-api/.venv/lib/python3.8/site-packages/ninja/responses.py", line 22, in default
    return super().default(o)
  File "/home/dcarnicer/workspace/projects/medip-api/.venv/lib/python3.8/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TicketHistorySchemaOut is not JSON serializable
```

apy.py
```
@api.get('/consumption/ticket-services/history/{language}/{payment_object_id}/')
def get_history(request, language: str, payment_object_id: int):
    with connection.cursor() as cursor:
        query = f"""
            SELECT
                op.purchase_id,
                CASE WHEN ol.name IS NULL
                THEN o.name
                ELSE ol.name END as offer_name,
                o.price,
                CASE WHEN o.running_time = 0
                THEN date_add(op.date, INTERVAL o.duration MINUTE)
                ELSE o.duration END as offer_duration
            FROM offer_purchases op
            INNER JOIN offers o ON op.offer_id = o.offer_id
            LEFT JOIN offer_localizations ol ON o.offer_id = ol.offer_id AND ol.languages_id = '{language}'
            INNER JOIN payment_objects p ON op.payment_object_id = p.id AND p.id = {payment_object_id}
        """

        cursor.execute(query)
        rows = cursor.fetchall()
        cursor.close()
    return [TicketHistorySchemaOut(*data) for data in rows]
```

schemas.py
```
from pydantic.dataclasses import dataclass
@dataclass
class TicketHistorySchemaOut:
    purchase_id: int
    offer_name: str
    price: int
    offer_duration: int
```

**Comment by vitalik** [comment]
@JFeldaca 
right.. you need to conert each item to dict
```Python
return [TicketHistorySchemaOut(*data).dict() for data in rows]
# ......................................^
```
