### ISSUE TITLE
Returning files through django-ninja

### ISSUE THREAD

**Issue by MattTPin** [vitalik/django-ninja#420]
Hello,

I'm able to successfully upload files using UploadedFile and File, however, I now need to be able to retrieve them from the media file in my backend and am unsure of how to return files through a get request. Something as simple as being able to download files directly from the Swagger UI would be greatly helpful. I've tried the following example...

```
from ninja import NinjaAPI
import zipfile

api = NinjaAPI()

@api.get("/test_download_file")
def test_download_file(request):
    archive = zipfile.ZipFile("./media/test_zip.zip", "r")
    return archive
```
Which throws an error as such...

```Traceback (most recent call last):
  File "/workspace/article_pipeline/venv/lib/python3.9/site-packages/ninja/operation.py", line 100, in run
    return self._result_to_response(request, result)
  File "/workspace/article_pipeline/venv/lib/python3.9/site-packages/ninja/operation.py", line 184, in _result_to_response
    return self.api.create_response(request, result, status=status)
  File "/workspace/article_pipeline/venv/lib/python3.9/site-packages/ninja/main.py", line 341, in create_response
    content = self.renderer.render(request, data, response_status=status)
  File "/workspace/article_pipeline/venv/lib/python3.9/site-packages/ninja/renderers.py", line 25, in render
    return json.dumps(data, cls=self.encoder_class, **self.json_dumps_params)
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/workspace/article_pipeline/venv/lib/python3.9/site-packages/ninja/responses.py", line 22, in default
    return super().default(o)
  File "/workspace/article_pipeline/venv/lib/python3.9/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ZipFile is not JSON serializable
```

I assume that JSON Serialization is a default method used when returning get requests and that I will need to set django-ninja to use an alternative serialization method that allows for a file (or file download link) to be returned instead. Any support would be greatly appreciated.

**Comment by vitalik** [comment]
@MattTPin 

You need to return django HttpResponse with included file (or [FileResponse from django](https://docs.djangoproject.com/en/4.0/ref/request-response/#fileresponse-objects) )

**Comment by MattTPin** [comment]
> @MattTPin
> 
> You need to return django HttpResponse with included file (or [FileResponse from django](https://docs.djangoproject.com/en/4.0/ref/request-response/#fileresponse-objects) )

Thank you! This was exactly what I needed! This code causes a downloadable file to be returned (on the Swagger UI a download button is returned).

```
from ninja import NinjaAPI
import zipfile
from django.http import HttpResponse

api = NinjaAPI()

@api.get("/test_download_file")
def test_download_file(request):
    archive = zipfile.ZipFile("./media/test_zip.zip", "r")
    response = HttpResponse(archive, content_type="application/zip")
    response["Content-Disposition"] = f"attachment; filename=archive.zip"

    return response
```
