### ISSUE TITLE
from_orm on ModelSchema

### ISSUE THREAD

**Issue by YoniSeedx** [vitalik/django-ninja#448]
When I want the response schema to be structured differently than the Django models, I add the `from_orm` function to the schema and manipulate whatever I need there.  That's worked great so far.

But when I try to define a `from_orm` function onto a ModelSchema, I get the error below:

```
TypeError: __class__ set to <class 'app.api.v4.schemas.book.BookOut'> defining 'BookOut' as <class 'app.api.v4.schemas.book.BookOut'>
```

I can use a regular Schema to work around the issue, but is there a better solution?

Example code:
```
class BookOut(ModelSchema):
    tags: Optional[List[str]]

    @classmethod
    def from_orm(cls, book: Book) -> "BookOut":
        book_out = super().from_orm(book)
        book_out.tags = [book.production_year, book.production_location]
        return book_out

    class Config:
        model = Book
        model_fields = [
            "name",
            "production_year",
            "production_location",
        ]
```

**Comment by vitalik** [comment]
Do you have full traceback ?

**Comment by vitalik** [comment]
closing for now as not possible to reporoduce

**Comment by vlada1g** [comment]
Same problem, can not overwrite from_orm function

**Comment by vitalik** [comment]
@vlada1g 

do you have example code and error traceback ?

**Comment by vlada1g** [comment]
I succed to overwrite from_orm function

**Comment by maxmorlocke** [comment]
It looks like overridding from_orm only explodes in this fashion when you attempt to call super().from_orm(obj=obj).  It does not explode without the super.

**Comment by bartoszgrabski** [comment]
@vitalik 

`pydantic==2.6.3`, `django-ninja==1.1.0`, `Django==4.2.1`

```
class Owner(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    owner_id = models.UUIDField(db_index=True)


class OwnerSchema(ModelSchema):
    class Meta:
        model = Owner
        fields = [
            'owner_id',
        ]

    def dict(self, *args, **kwargs):
        obj = super().dict(*args, **kwargs)
        obj['owner_id'] = obj['owner_id'].hex
        return obj
```

throws on `python manage.py test`:

```
Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/test.py", line 24, in run_from_argv
    super().run_from_argv(argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/test.py", line 68, in handle
    failures = test_runner.run_tests(test_labels)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/test/runner.py", line 1060, in run_tests
    self.run_checks(databases)
  File "/usr/local/lib/python3.11/site-packages/django/test/runner.py", line 977, in run_checks
    call_command("check", verbosity=self.verbosity, databases=databases)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 194, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/check.py", line 76, in handle
    self.check(
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/config/urls.py", line 3, in <module>
    from config.api import xxx_api
  File "/app/config/api.py", line 3, in <module>
    from mods.xxx.api import router as xxx_router
  File "/app/mods/xxx/api.py", line 10, in <module>
    from mods.xxx.schemas import (
  File "/app/mods/xxx/schemas.py", line 59, in <module>
    class OwnerSchema(ModelSchema):
TypeError: __class__ set to <class 'mods.xxx.schemas.OwnerSchema'> defining 'OwnerSchema' as <class 'mods.xxx.schemas.OwnerSchema'>
```
