### ISSUE TITLE
[BUG] UploadedFile breaks SwaggerUI after v0.18.0, works with v0.17.0

### ISSUE THREAD

**Issue by lesser-panda** [vitalik/django-ninja#520]
**Describe the bug**
I am trying to create an Endpoint that allows file uploads. I followed the instructions here (https://django-ninja.rest-framework.com/tutorial/file-params/). But once I added this endpoint to my project, it breaks the SwaggerUI.

Same project works <= v0.17.0, but breaks after v0.18.0

```
from ninja import NinjaAPI, File
from ninja.files import UploadedFile

@api.post("/upload")
def upload(request, file: UploadedFile = File(...)):
    data = file.read()
    return {'name': file.name, 'len': len(data)}
```

Error message:
```
[03/Aug/2022 03:17:27] "GET /api/docs HTTP/1.1" 200 962
Internal Server Error: /api/openapi.json
Traceback (most recent call last):
  File "/home/zhongyuan/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/zhongyuan/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zhongyuan/.local/lib/python3.8/site-packages/ninja/openapi/views.py", line 35, in openapi_json
    schema = api.get_openapi_schema()
  File "/home/zhongyuan/.local/lib/python3.8/site-packages/ninja/main.py", line 419, in get_openapi_schema
    return get_schema(api=self, path_prefix=path_prefix)
  File "/home/zhongyuan/.local/lib/python3.8/site-packages/ninja/openapi/schema.py", line 40, in get_schema
    openapi = OpenAPISchema(api, path_prefix)
  File "/home/zhongyuan/.local/lib/python3.8/site-packages/ninja/openapi/schema.py", line 62, in __init__
    ("paths", self.get_paths()),
  File "/home/zhongyuan/.local/lib/python3.8/site-packages/ninja/openapi/schema.py", line 77, in get_paths
    path_methods = self.methods(path_view.operations)
  File "/home/zhongyuan/.local/lib/python3.8/site-packages/ninja/openapi/schema.py", line 86, in methods
    operation_details = self.operation_details(op)
  File "/home/zhongyuan/.local/lib/python3.8/site-packages/ninja/openapi/schema.py", line 114, in operation_details
    body = self.request_body(operation)
  File "/home/zhongyuan/.local/lib/python3.8/site-packages/ninja/openapi/schema.py", line 227, in request_body
    schema, required = self._create_schema_from_model(
  File "/home/zhongyuan/.local/lib/python3.8/site-packages/ninja/openapi/schema.py", line 185, in _create_schema_from_model
    schema = model_schema(
  File "pydantic/schema.py", line 167, in pydantic.schema.model_schema
  File "pydantic/schema.py", line 548, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 589, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 236, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 303, in pydantic.schema.get_field_schema_validations
TypeError: __modify_schema__() missing 1 required positional argument: 'field'
```

My `api.py`:

```
from ninja import NinjaAPI, File
from ninja.files import UploadedFile

api = NinjaAPI()

@api.post("/upload")
def upload(request, file: UploadedFile):
    data = file.read()
    return {'name': file.name, 'len': len(data)}
```

**Versions (please complete the following information):**
 - Python version: [3.8.10]
 - Django version: [4.0.6]
 - Django-Ninja version: [0.19.1]

**Comment by lesser-panda** [comment]
Sorry turns out to be an environment issue. Tested in docker and it's working. Closing this now.

**Comment by robinsandstrom** [comment]
I am getting the same error. Are you sure it's not working in Docker because of a requirements.txt file with an older version of django-ninja @lesser-panda ?

**Comment by bakapiano** [comment]
> I am getting the same error. Are you sure it's not working in Docker because of a requirements.txt file with an older version of django-ninja @lesser-panda ?

I fix this error by upgrade `pydantic` dependency version from 1.8.2 to 1.10.2, it may work for you too.
