### ISSUE TITLE
[BUG] file upload  openapi bad

### ISSUE THREAD

**Issue by defnngj** [vitalik/django-ninja#541]
**Describe the bug**

```python
from ninja import NinjaAPI, File
from ninja.files import UploadedFile
from ninja import Router

router = Router(tags=["file"])


@router.post("/upload")
def upload(request, file: UploadedFile = File(...)):
    data = file.read()
    return {'name': file.name, 'len': len(data)}

```

![image](https://user-images.githubusercontent.com/1000588/186927387-7f9ab403-b981-43ad-80ac-c5ac19a2da3a.png)

django error log:
```py
Django version 4.0.6, using settings 'backend.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[26/Aug/2022 22:29:52] "GET /api/docs HTTP/1.1" 200 788
Internal Server Error: /api/openapi.json
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python38\lib\site-packages\ninja\openapi\views.py", line 35, in openapi_json
    schema = api.get_openapi_schema()
  File "C:\Python38\lib\site-packages\ninja\main.py", line 419, in get_openapi_schema
    return get_schema(api=self, path_prefix=path_prefix)
  File "C:\Python38\lib\site-packages\ninja\openapi\schema.py", line 40, in get_schema
    openapi = OpenAPISchema(api, path_prefix)
  File "C:\Python38\lib\site-packages\ninja\openapi\schema.py", line 62, in __init__
    ("paths", self.get_paths()),
  File "C:\Python38\lib\site-packages\ninja\openapi\schema.py", line 77, in get_paths
    path_methods = self.methods(path_view.operations)
  File "C:\Python38\lib\site-packages\ninja\openapi\schema.py", line 86, in methods
    operation_details = self.operation_details(op)
  File "C:\Python38\lib\site-packages\ninja\openapi\schema.py", line 114, in operation_details
    body = self.request_body(operation)
  File "C:\Python38\lib\site-packages\ninja\openapi\schema.py", line 227, in request_body
    schema, required = self._create_schema_from_model(
  File "C:\Python38\lib\site-packages\ninja\openapi\schema.py", line 185, in _create_schema_from_model
    schema = model_schema(
  File "pydantic\schema.py", line 167, in pydantic.schema.model_schema
  File "pydantic\schema.py", line 548, in pydantic.schema.model_process_schema
  File "pydantic\schema.py", line 589, in pydantic.schema.model_type_schema
  File "pydantic\schema.py", line 236, in pydantic.schema.field_schema
  File "pydantic\schema.py", line 303, in pydantic.schema.get_field_schema_validations
TypeError: __modify_schema__() missing 1 required positional argument: 'field'
```
**Versions (please complete the following information):**
 - Python version: [e.g. 3.8]
 - Django version: [e.g. 4.0.6]
 - Django-Ninja version: [e.g. 0.19.1]

**Comment by defnngj** [comment]
`pydantic`  version problems.

```shell
pip install pydantic==1.9.1
```

It's  work~!
