### ISSUE TITLE
[BUG] TypeError: unhashable type: 'slice'

### ISSUE THREAD

**Issue by ddzyx** [vitalik/django-ninja#548]
```Python
@router.get("/movielist/{movie_type_id}", response=List[MovieSchemaOut])
@paginate
def list_movie(request, movie_type_id: int):
    a = MovieType.objects.filter(id=movie_type_id).first()
    data = [MovieSchemaOut.from_orm(i).dict() for i in qs]
    return {"msg": "success", "data": data}`
```
Error code after running

````
<html>
<body>
<!--StartFragment-->

nted | Error: Internal Server ErrorResponse bodyDownloadTraceback (most recent call last):   File "D:\Program Files (x86)\Anaconda3\envs\django\lib\site-packages\ninja\operation.py", line 99, in run     result = self.view_func(request, **values)   File "D:\Program Files (x86)\Anaconda3\envs\django\lib\site-packages\ninja\pagination.py", line 145, in view_with_pagination     result = paginator.paginate_queryset(   File "D:\Program Files (x86)\Anaconda3\envs\django\lib\site-packages\ninja\pagination.py", line 69, in paginate_queryset     "items": queryset[offset : offset + limit], TypeError: unhashable type: 'slice'
-- | --


<!--EndFragment-->
</body>
</html>
```

**Comment by hiaselhans** [comment]
@ddzyx , please use proper formatting and code blocks.

please read the docs for pagination: https://django-ninja.rest-framework.com/guides/response/pagination/

the `@pagination` decorator can only work with a function returning a queryset

**Comment by vitalik** [comment]
@ddzyx

the `paginage` expects you to return a queryset:


```Python
@router.get("/movielist/{movie_type_id}", response=List[MovieSchemaOut])
@paginate
def list_movie(request, movie_type_id: int):
    qs = Movie.objects.filter(type_id=movie_type_id)
    return qs
```
