### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by scandel** [vitalik/django-ninja#582]
**Describe the bug**
I would like to have the response schema to be structured differently than the Django models, so I wanted to add fields in the `__init__` of a schema based on `ModelSchema`, but got : 
```
 TypeError: __class__ set to <class 'myapp.api.gene.GeneSchema'> defining 'GeneSchema' as <class 'myapp.api.gene.GeneSchema'>
```
Relevant portion of code: 
```python
class GeneSchema(ModelSchema):
    class Config:
        model = Gene
        model_fields = ['id', 'name', 'default_sort_order', 'score']

    def __init__(self, **data: Any):
        super().__init__(**data)
        # Wanted to do some stuff here
```
Traceback: 
```
app_1       | Performing system checks...
app_1       | 
app_1       | Exception in thread django-main-thread:
app_1       | Traceback (most recent call last):
app_1       |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
app_1       |     self.run()
app_1       |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
app_1       |     self._target(*self._args, **self._kwargs)
app_1       |   File "/usr/local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
app_1       |     fn(*args, **kwargs)
app_1       |   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
app_1       |     self.check(display_num_errors=True)
app_1       |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 487, in check
app_1       |     all_issues = checks.run_checks(
app_1       |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
app_1       |     new_errors = check(app_configs=app_configs, databases=databases)
app_1       |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
app_1       |     return check_resolver(resolver)
app_1       |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
app_1       |     return check_method()
app_1       |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 480, in check
app_1       |     for pattern in self.url_patterns:
app_1       |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
app_1       |     res = instance.__dict__[self.name] = self.func(instance)
app_1       |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 696, in url_patterns
app_1       |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
app_1       |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
app_1       |     res = instance.__dict__[self.name] = self.func(instance)
app_1       |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
app_1       |     return import_module(self.urlconf_name)
app_1       |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
app_1       |     return _bootstrap._gcd_import(name[level:], package, level)
app_1       |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
app_1       |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
app_1       |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
app_1       |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
app_1       |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
app_1       |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
app_1       |   File "/usr/src/app/main/urls.py", line 20, in <module>
app_1       |     from .api import api_cookie
app_1       |   File "/usr/src/app/main/api.py", line 5, in <module>
app_1       |     from myapp.api.gene import router_cookie as gene_router
app_1       |   File "/usr/src/app/myapp/api/gene.py", line 66, in <module>
app_1       |     class GeneSchema(ModelSchema):
app_1       | TypeError: __class__ set to <class 'myapp.api.gene.GeneSchema'> defining 'GeneSchema' as <class 'myapp.api.gene.GeneSchema'>
```

**Versions (please complete the following information):**
 - Python version: 3.10
 - Django version: 4.0.8
 - Django-Ninja version: 0.19.1]

Related to #448 ?

**Comment by AndreaGiardini** [comment]
I am facing the same issue since I would also like a different schema for the output (with fewer fields).
Is the only way to define a separate `ModelSchema` for input and a separate `Model` for output? @vitalik

**Comment by vitalik** [comment]
@AndreaGiardini 

well pydantc does not really allow to change fields at runtime after initialized

what you can do is define id as Optional

```Python
class GeneSchema(ModelSchema):
    id: int = None  # allow id to be empty
    class Config:
        model = Gene
        model_fields = ['name', 'default_sort_order', 'score']  # !!! no 'id' here !!!!

```

this way you can use this model as input and output
