### ISSUE TITLE
[BUG] Hot Reload Hanging

### ISSUE THREAD

**Issue by metersk** [vitalik/django-ninja#648]
**Describe the bug**
I'm noticing that hot reload hangs quite often, which requires me to tear down and bring up my container.  Here is the traceback for the last time this happened to me.

```
kingdom-django-api-1  | Watching for file changes with StatReloader
kingdom-django-api-1  | Performing system checks...
kingdom-django-api-1  |
kingdom-django-api-1  | System check identified no issues (0 silenced).
kingdom-django-api-1  | January 09, 2023 - 22:27:21
kingdom-django-api-1  | Django version 4.1.2, using settings 'api.settings'
kingdom-django-api-1  | Starting development server at http://0.0.0.0:8000/
kingdom-django-api-1  | Quit the server with CONTROL-C.
kingdom-django-api-1  | /opt/app/api/kingdom/views.py changed, reloading.
kingdom-django-api-1  | Watching for file changes with StatReloader
kingdom-django-api-1  | Performing system checks...
kingdom-django-api-1  |
kingdom-django-api-1  | Exception in thread django-main-thread:
kingdom-django-api-1  | Traceback (most recent call last):
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
kingdom-django-api-1  |     self.run()
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
kingdom-django-api-1  |     self._target(*self._args, **self._kwargs)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
kingdom-django-api-1  |     fn(*args, **kwargs)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
kingdom-django-api-1  |     self.check(display_num_errors=True)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 475, in check
kingdom-django-api-1  |     all_issues = checks.run_checks(
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
kingdom-django-api-1  |     new_errors = check(app_configs=app_configs, databases=databases)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
kingdom-django-api-1  |     return check_resolver(resolver)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
kingdom-django-api-1  |     return check_method()
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
kingdom-django-api-1  |     for pattern in self.url_patterns:
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
kingdom-django-api-1  |     res = instance.__dict__[self.name] = self.func(instance)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
kingdom-django-api-1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
kingdom-django-api-1  |     res = instance.__dict__[self.name] = self.func(instance)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
kingdom-django-api-1  |     return import_module(self.urlconf_name)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
kingdom-django-api-1  |     return _bootstrap._gcd_import(name[level:], package, level)
kingdom-django-api-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
kingdom-django-api-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
kingdom-django-api-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
kingdom-django-api-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
kingdom-django-api-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
kingdom-django-api-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
kingdom-django-api-1  |   File "/opt/app/api/api.py", line 7, in <module>
kingdom-django-api-1  |     from api.kingdom.views import router as kingdom_router
kingdom-django-api-1  |   File "/opt/app/api/kingdom/views.py", line 105, in <module>
kingdom-django-api-1  |     def get_plate(request, response=PlateSchema):
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/ninja/router.py", line 228, in decorator
kingdom-django-api-1  |     self.add_api_operation(
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/ninja/router.py", line 275, in add_api_operation
kingdom-django-api-1  |     path_view.add_operation(
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/ninja/operation.py", line 299, in add_operation
kingdom-django-api-1  |     operation = OperationClass(
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/ninja/operation.py", line 64, in __init__
kingdom-django-api-1  |     self.signature = ViewSignature(self.path, self.view_func)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/ninja/signature/details.py", line 75, in __init__
kingdom-django-api-1  |     self.models: TModels = self._create_models()
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/ninja/signature/details.py", line 155, in _create_models
kingdom-django-api-1  |     model_cls = type(cls_name, (base_cls,), attrs)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 198, in __new__
kingdom-django-api-1  |     fields[ann_name] = ModelField.infer(
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/pydantic/fields.py", line 506, in infer
kingdom-django-api-1  |     return cls(
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/pydantic/fields.py", line 436, in __init__
kingdom-django-api-1  |     self.prepare()
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/pydantic/fields.py", line 557, in prepare
kingdom-django-api-1  |     self.populate_validators()
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/pydantic/fields.py", line 831, in populate_validators
kingdom-django-api-1  |     *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/pydantic/validators.py", line 765, in find_validators
kingdom-django-api-1  |     raise RuntimeError(f'no validator found for {type_}, see `arbitrary_types_allowed` in Config')
kingdom-django-api-1  | RuntimeError: no validator found for <class 'ninja.schema.ResolverMetaclass'>, see `arbitrary_types_allowed` in Config
```

**Versions (please complete the following information):**
 - Python version: 3.10.7
 - Django version: Django==4.1.2
 - Django-Ninja version: django-ninja==0.19.1
 - Pydantic version: pydantic==1.10.2

**Comment by metersk** [comment]
```
kingdom-django-api-1  | Exception in thread django-main-thread:
kingdom-django-api-1  | Traceback (most recent call last):
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
kingdom-django-api-1  |     self.run()
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
kingdom-django-api-1  |     self._target(*self._args, **self._kwargs)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
kingdom-django-api-1  |     fn(*args, **kwargs)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
kingdom-django-api-1  |     self.check(display_num_errors=True)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 475, in check
kingdom-django-api-1  |     all_issues = checks.run_checks(
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
kingdom-django-api-1  |     new_errors = check(app_configs=app_configs, databases=databases)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
kingdom-django-api-1  |     return check_resolver(resolver)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
kingdom-django-api-1  |     return check_method()
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
kingdom-django-api-1  |     for pattern in self.url_patterns:
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
kingdom-django-api-1  |     res = instance.__dict__[self.name] = self.func(instance)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
kingdom-django-api-1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
kingdom-django-api-1  |     res = instance.__dict__[self.name] = self.func(instance)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
kingdom-django-api-1  |     return import_module(self.urlconf_name)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
kingdom-django-api-1  |     return _bootstrap._gcd_import(name[level:], package, level)
kingdom-django-api-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
kingdom-django-api-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
kingdom-django-api-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
kingdom-django-api-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
kingdom-django-api-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
kingdom-django-api-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
kingdom-django-api-1  |   File "/opt/app/api/api.py", line 6, in <module>
kingdom-django-api-1  |     from api.chemistry.views import router as chemistry_router
kingdom-django-api-1  |   File "/opt/app/api/chemistry/views.py", line 7, in <module>
kingdom-django-api-1  |     from api.chemistry import helpers
kingdom-django-api-1  |   File "/opt/app/api/chemistry/helpers.py", line 14, in <module>
kingdom-django-api-1  |     from api.chemistry.schemas import (
kingdom-django-api-1  |   File "/opt/app/api/chemistry/schemas.py", line 7, in <module>
kingdom-django-api-1  |     from api.kingdom.schemas import ProjectSchemaOut, PlateSchemaOut
kingdom-django-api-1  | ImportError: cannot import name 'PlateSchemaOut' from 'api.kingdom.schemas' (/opt/app/api/kingdom/schemas.py)
kingdom-django-api-1  | /opt/app/api/chemistry/schemas.py changed, reloading.
kingdom-django-api-1  | Watching for file changes with StatReloader
kingdom-django-api-1  | Performing system checks...
kingdom-django-api-1  |
kingdom-django-api-1  | Exception in thread django-main-thread:
kingdom-django-api-1  | Traceback (most recent call last):
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
kingdom-django-api-1  |     self.run()
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
kingdom-django-api-1  |     self._target(*self._args, **self._kwargs)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
kingdom-django-api-1  |     fn(*args, **kwargs)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
kingdom-django-api-1  |     self.check(display_num_errors=True)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 475, in check
kingdom-django-api-1  |     all_issues = checks.run_checks(
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
kingdom-django-api-1  |     new_errors = check(app_configs=app_configs, databases=databases)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
kingdom-django-api-1  |     return check_resolver(resolver)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
kingdom-django-api-1  |     return check_method()
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
kingdom-django-api-1  |     for pattern in self.url_patterns:
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
kingdom-django-api-1  |     res = instance.__dict__[self.name] = self.func(instance)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
kingdom-django-api-1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
kingdom-django-api-1  |     res = instance.__dict__[self.name] = self.func(instance)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
kingdom-django-api-1  |     return import_module(self.urlconf_name)
kingdom-django-api-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
kingdom-django-api-1  |     return _bootstrap._gcd_import(name[level:], package, level)
kingdom-django-api-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
kingdom-django-api-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
kingdom-django-api-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
kingdom-django-api-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
kingdom-django-api-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
kingdom-django-api-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
kingdom-django-api-1  |   File "/opt/app/api/api.py", line 6, in <module>
kingdom-django-api-1  |     from api.chemistry.views import router as chemistry_router
kingdom-django-api-1  |   File "/opt/app/api/chemistry/views.py", line 7, in <module>
kingdom-django-api-1  |     from api.chemistry import helpers
kingdom-django-api-1  |   File "/opt/app/api/chemistry/helpers.py", line 14, in <module>
kingdom-django-api-1  |     from api.chemistry.schemas import (
kingdom-django-api-1  |   File "/opt/app/api/chemistry/schemas.py", line 23, in <module>
kingdom-django-api-1  |     class ChemistrySampleSubmissionSchemaOut(Schema):
kingdom-django-api-1  |   File "/opt/app/api/chemistry/schemas.py", line 32, in ChemistrySampleSubmissionSchemaOut
kingdom-django-api-1  |     plate: PlateSchemaOut = None
kingdom-django-api-1  | NameError: name 'PlateSchemaOut' is not defined. Did you mean: 'ProjectSchemaOut'?
```

**Comment by vitalik** [comment]
@metersk 

well something is up with your schemes or circular import ? - hard to tell without inspect the code 

like try to investigate this one:
```
plate: PlateSchemaOut = None
kingdom-django-api-1  | NameError: name 'PlateSchemaOut' is not defined. Did you mean: 'ProjectSchemaOut'
```

it tells that you using PlateSchemaOut without importing it ?

**Comment by metersk** [comment]
sorry, i should have been more clear.  even after the error is fixed in both of those cases, the development server does not restart, it just hangs.  for example, in both of the instances above where it is hanging on an error -- i fix the error, notice it continues to hang indefinitely, tear down and bring my container up again, and everything works fine.  this happens a handful of times per day as i'm developing.

**Comment by vitalik** [comment]
well, unfortunatelly there are no clues to how to reproduce this

if you can isolate it to some smaller or example - please reopen the ticket
