### ISSUE TITLE
[BUG] Cannot import name 'NinjaAPI' from 'ninja'  

### ISSUE THREAD

**Issue by hakanoktay** [vitalik/django-ninja#650]
**Cannot import name 'NinjaAPI' from 'ninja'**
```python
cannot import name 'NinjaAPI' from 'ninja' (/usr/local/lib/python3.9/site-packages/ninja/__init__.py)
```
Hi,
After hours of research, trying several different docker images, I thought I'd write it down. Actually it was working yesterday, I don't really understand what happened. I did a clean docker install, a clean django install several times and got the same error. I think something happened in the matrix (Matrix from movie). There is no other explanation for something that was working before to stop working like this.

The codes are as follows:

**Versions (please complete the following information):**
- Python version: [3.9.16]
- Django version: [4.1.5]
- Django-Ninja version: [1.11.1]
- Docker Image version: [python:3.9.16-slim-buster, python:1.03-bullseye]

**Code:**
```python
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from ninja import NinjaAPI

@api.get("/add")
def add(request, a: int, b: int):
    return {"result": a + b}

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('apps.home.urls'),name='home'),
    path("api/", api.urls),
]

urlpatterns += staticfiles_urlpatterns()
```

**Error:**
```python
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/py_test/backend/core/urls.py", line 8, in <module>
    from ninja import NinjaAPI
ImportError: cannot import name 'NinjaAPI' from 'ninja' (/usr/local/lib/python3.9/site-packages/ninja/__init__.py)
```

**Comment by vitalik** [comment]
@hakanoktay maybe you installed `ninja` instead of `django-ninja` ?

**Comment by hakanoktay** [comment]
> 
hi Vitalik,
I am sorry to say (sorry for myself :)) you are absolutely right. 

I lost a lot of time because I didn't see the mistake I made, but I was most upset that I couldn't use ninja and django because of the problem. but now it works like a cheetah.
thank you for your response.
