### ISSUE TITLE
Queryset inside OuterSchema is not evaluated automatically

### ISSUE THREAD

**Issue by tarelda** [vitalik/django-ninja#659]
I am trying to implement search schema where keys of output dict are bound to querysets for particular data type. At the moment, just the customers, but I think following snippet will explain the idea.

```
class CustomerSchema(ModelSchema):
    class Config:
        model = customers.models.Customer
        model_fields = ['id', 'lastname', 'name']

class SearchSchema(Schema):
    customers: List[CustomerSchema]
```

After that I make the response like this:

```
@api.get("search", response=SearchSchema)
def search(request, query: str):
    result = {}
    result["customers"] = customers.models.get_search_qs(query)
    return result
```

But this yields following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ninja/operation.py", line 100, in run
    return self._result_to_response(request, result, temporal_response)
  File "/usr/local/lib/python3.8/dist-packages/ninja/operation.py", line 196, in _result_to_response
    result = response_model.from_orm(resp_object).dict(
  File "/usr/local/lib/python3.8/dist-packages/ninja/schema.py", line 164, in from_orm
    return super().from_orm(obj)
  File "pydantic/main.py", line 579, in pydantic.main.BaseModel.from_orm
pydantic.error_wrappers.ValidationError: 1 validation error for NinjaResponseSchema
response -> customers
  value is not a valid list (type=type_error.list)
```

I can make it work by creating list manually, but I don't understand why previous approach doesn't work:

```
@api.get("search", response=SearchSchema)
def search(request, query: str):
    result = {}
    result["customers"] = [CustomerSchema.from_orm(c) for c in customers.models.get_search_qs(query)]
    return result
```

**Comment by vitalik** [comment]
@tarelda

try:
```Python
result["customers"] = list(customers.models.get_search_qs(query))
```

**Comment by tarelda** [comment]
> @tarelda
> 
> try:
> 
> ```python
> result["customers"] = list(customers.models.get_search_qs(query))
> ```

I tried it too. I am just confused that I can do smth like this:

```
@api.get("search", response=List[CustomerSchema])
def search(request, query: str):
    return customers.models.get_search_qs(query)
```

But not the way I have shown previously.
@vitalik What do you consider more correct approach? Since automagically qs to list conversion doesn't work, I am fine with list or from_orm conversion.
