### ISSUE TITLE
Dose Django Ninja Support Async ? (from django 4.1 )

### ISSUE THREAD

**Issue by azataiot** [vitalik/django-ninja#671]
As the django documentation describes here, Django version 4.1 already support a lot of the async ORM functions, And i used them in my code, but i still had errors working with django ninja.
After cheking the errors and logs, i discovered that it is django ninja having problems with supporting async functions.

Dose it support native django 4.1 async functions ? If not, is there any working code or plan for this ? 

Thanks.

**Comment by vitalik** [comment]
@azataiot 

should support for most of the cases (except pagination that is currently sync only)

which case did not work for you ?

**Comment by azataiot** [comment]
> @azataiot
> 
> should support for most of the cases (except pagination that is currently sync only)
> 
> which case did not work for you ?

```python
    async def read_last(self) -> QuerySet:
        obj = await self.table.objects.alast()
        return obj
```
This is my function to get the last object from the django ORM.
```python
# JBS Index Page
JBSSchema = create_schema(JBS, depth=1)
```
This was my schema, and 
```python
async def read_jbs(request):
    repo = AsyncRepository(JBS, request)
    ret = await repo.read_last()
    print(type(ret))
    print(ret.__dict__)
    JBSSchema.from_orm(ret.__dict__)
    print(JBSSchema)
    data = await serializers.serialize("json", ret)
    print("After Get last")
    return ret
```

and this is the console outputs:
```
/Users/azat/Developer/Django/izdinish/venv/bin/python -m uvicorn izdinish.asgi:application --reload 
INFO:     Will watch for changes in these directories: ['/']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [28135] using StatReload
INFO:     Started server process [28137]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
You cannot call this from an async context - use a thread or sync_to_async.
Traceback (most recent call last):
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 189, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'jbs_default_site'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/ninja/operation.py", line 260, in run
    return self._result_to_response(request, result, temporal_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/ninja/operation.py", line 196, in _result_to_response
    result = response_model.from_orm(resp_object).dict(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/ninja/schema.py", line 164, in from_orm
    return super().from_orm(obj)
           ^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 578, in pydantic.main.BaseModel.from_orm
  File "pydantic/main.py", line 1077, in pydantic.main.validate_model
  File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1101, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1148, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 318, in pydantic.class_validators._generic_validator_basic.lambda13
  File "pydantic/main.py", line 714, in pydantic.main.BaseModel.validate
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/ninja/schema.py", line 164, in from_orm
    return super().from_orm(obj)
           ^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 578, in pydantic.main.BaseModel.from_orm
  File "pydantic/main.py", line 1056, in pydantic.main.validate_model
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/ninja/schema.py", line 67, in get
    return self[key]
           ~~~~^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/ninja/schema.py", line 54, in __getitem__
    item = getattr(self._obj, key)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 207, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 170, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/query.py", line 646, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 24, in inner
    raise SynchronousOnlyOperation(message)
django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
You cannot call this from an async context - use a thread or sync_to_async.
Traceback (most recent call last):
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 189, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'jbs_default_site'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/ninja/operation.py", line 260, in run
    return self._result_to_response(request, result, temporal_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/ninja/operation.py", line 196, in _result_to_response
    result = response_model.from_orm(resp_object).dict(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/ninja/schema.py", line 164, in from_orm
    return super().from_orm(obj)
           ^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 578, in pydantic.main.BaseModel.from_orm
  File "pydantic/main.py", line 1077, in pydantic.main.validate_model
  File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1101, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1148, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 318, in pydantic.class_validators._generic_validator_basic.lambda13
  File "pydantic/main.py", line 714, in pydantic.main.BaseModel.validate
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/ninja/schema.py", line 164, in from_orm
    return super().from_orm(obj)
           ^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 578, in pydantic.main.BaseModel.from_orm
  File "pydantic/main.py", line 1056, in pydantic.main.validate_model
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/ninja/schema.py", line 67, in get
    return self[key]
           ~~~~^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/ninja/schema.py", line 54, in __getitem__
    item = getattr(self._obj, key)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 207, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 170, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/query.py", line 646, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/izdinish/venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 24, in inner
    raise SynchronousOnlyOperation(message)
django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
Internal Server Error: /jbs
Internal Server Error: /jbs
<class 'api.models.JBS'>
{'_state': <django.db.models.base.ModelState object at 0x107d654d0>, 'id': 1, 'uid': UUID('9f7fab62-9a8b-4f0f-a8b7-958b84b972b8'), 'jbs_universal_id': 'izdinish', 'jbs_admin_full_name': 'Murat Orhun', 'jbs_admin_email': 'example@gmail.com', 'jbs_default_site_id': 1, 'jbs_server_status': 'OK', 'jsb_enable_auto_discovery': True, 'jsb_public_visible': True, 'jsb_ios_link': '', 'jsb_android_link': '', 'created': datetime.datetime(2023, 1, 30, 9, 0, 2, 484703, tzinfo=datetime.timezone.utc), 'last_updated': datetime.datetime(2023, 1, 30, 9, 0, 2, 484746, tzinfo=datetime.timezone.utc)}
After Get last
INFO:     127.0.0.1:54533 - "GET /jbs HTTP/1.1" 500 Internal Server Error
```
I guess the operation.py includes some sync/async code which is not compatible with django 4.1.

**Comment by azataiot** [comment]
update: Can confirm that the error happens inside the `create_schema` function when the `depth` is not `0`. if the `depth` is 0, no error returned.

that means, 
``` python
# JBS Index Page
JBSSchema = create_schema(JBS, depth=0)


@api.get("/jbs", response={
    200: JBSSchema
})
async def read_jbs(request):
    repo = AsyncRepository(JBS, request)
    ret = await repo.read_last()
    print(type(ret))
    print(ret.__dict__)
    print("After Get last")
    return ret
``` this is working with no error. only difference is `depth=0`

**Comment by azataiot** [comment]
update: 
I guess this came from the ninja's Django reverse functions where it calls some sync code, and when we switch to async, it dose not await.

**Comment by vitalik** [comment]
@azataiot 

Your problem is probably here:
```
ret = await repo.read_last()
```

the read_last reads only top level object and does not read related in the same query - and they are getting evaluated (extra sql queries) when rendering starts

basically what you need to do is make sure that read_last queries that fat object with depth using [select_related](https://docs.djangoproject.com/en/4.1/ref/models/querysets/#select-related)

**Comment by azataiot** [comment]
@vitalik ok, i will test it noe.

**Comment by azataiot** [comment]
I have created an application and setup the endpoints, 
#https://github.com/azataiot/dj-ninja/issues/1#issue-1575878619, after doing so, when using create_schema for default User model, I also got similar error, 

```python
You cannot call this from an async context - use a thread or sync_to_async.
Traceback (most recent call last):
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/operation.py", line 260, in run
    return self._result_to_response(request, result, temporal_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/operation.py", line 196, in _result_to_response
    result = response_model.from_orm(resp_object).dict(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/schema.py", line 164, in from_orm
    return super().from_orm(obj)
           ^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 578, in pydantic.main.BaseModel.from_orm
  File "pydantic/main.py", line 1077, in pydantic.main.validate_model
  File "pydantic/fields.py", line 895, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 928, in pydantic.fields.ModelField._validate_sequence_like
  File "pydantic/fields.py", line 1094, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1101, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1148, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 318, in pydantic.class_validators._generic_validator_basic.lambda13
  File "pydantic/main.py", line 714, in pydantic.main.BaseModel.validate
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/schema.py", line 164, in from_orm
    return super().from_orm(obj)
           ^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 578, in pydantic.main.BaseModel.from_orm
  File "pydantic/main.py", line 1056, in pydantic.main.validate_model
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/schema.py", line 67, in get
    return self[key]
           ~~~~^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/schema.py", line 63, in __getitem__
    return self._convert_result(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/schema.py", line 73, in _convert_result
    return list(result.all())
           ^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/django/db/models/query.py", line 394, in __iter__
    self._fetch_all()
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 24, in inner
    raise SynchronousOnlyOperation(message)
django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
Internal Server Error: /async/users

```

**Comment by azataiot** [comment]
@vitalik creating UserSchema (default from `from django.contrib.auth.models import User`) also encounters the same error, but, creating the UserSchema with `Schema` class from ninja works. 

check: 
- #https://github.com/azataiot/dj-ninja/issues/1#issuecomment-1422515532
- #https://github.com/azataiot/dj-ninja/issues/1#issuecomment-1422516355
- #https://github.com/azataiot/dj-ninja/issues/1#issuecomment-1422516970 
- #https://github.com/azataiot/dj-ninja/issues/1#issuecomment-1422518087
- #https://github.com/azataiot/dj-ninja/issues/1#issuecomment-1422521962 

I also pushed the demo code to Github, you can debug the code which i am using on brach `ninja-async-uvicorn`
#https://github.com/azataiot/dj-ninja/tree/ninja-async-uvicorn

**Comment by azataiot** [comment]
> can you check this @vitalik 
https://github.com/azataiot/dj-ninja/tree/ninja-async-uvicorn

**Comment by azataiot** [comment]
to avoid that my code may cause problems, i setup a new project only with django, uvicorn, gunicorn and django-ninja, also tested models and code with sync mode first, and it worked. now i faced the same problem, after i switched to the async. 

This time it giving error not only on my own code, but any model referencing the django User model.

**Comment by vitalik** [comment]
@azataiot 

if I'm not mistaken -  you should pass fields select_related method  :
```Python 
await One.objects.select_related('user').afirst()
# --------------------------------^
```

**Comment by azataiot** [comment]
> 

Usually we do not, also check the code for this:

```python
@router.get("/async/one/deep", response={
    200: List[OneSchemaDeep]
})
async def async_get_one_deep_all(request):
    objs = []
    async for each in One.objects.select_related().all():
        objs.append(each)
    return objs
```

**Comment by azataiot** [comment]
> 

same endpoint works for 'UserSchemaManually' created using the Schema Class, but when the UserSchema created with `create_schema` it dose not. 

So i am guessing the code above is correct, there might be something wrong on `create_schema`

**Comment by vitalik** [comment]
well... too much chaos - would you be able to isolate somehow code that fails (model + schema + view function) ?

**Comment by azataiot** [comment]
> well... too much chaos - would you be able to isolate somehow code that fails (model + schema + view function) ?

yes, 
let's do this:

Model:
```python
from django.contrib.auth.models import User
```

Schema:
```python
from ninja import Schema
from ninja.orm import create_schema
from django.contrib.auth.models import User

# dose not work
UserSchema = create_schema(User, depth=0)

# works
class UserSchemaManually(Schema):
    id: int
    username: str
    first_name: str
    last_name: str
    password: str
    last_login: datetime
    is_superuser: bool
    email: str
```
View:
```python
from typing import List
from ninja import Router 
from ninja_demo.schemas.user import UserSchema, UserSchemaManually
router = Router()

# dose not work
@router.get("/async/users", response={
    200: List[UserSchema]
})
async def async_get_users(request):
    objs = []
    async for each in User.objects.select_related().all():
        objs.append(each)
    first = objs[0]
    print(first)
    print(first.__dict__)
    return objs


# works
@router.get("/async/users/manually", response={
    200: List[UserSchemaManually]
})
async def async_get_users_manually(request):
    objs = []
    async for each in User.objects.select_related().all():
        objs.append(each)
    return objs
```

**Comment by oystersuki** [comment]
```python
@router.get("/async/users", response={
    200: List[UserSchema]
})
async def async_get_users(request):
    objs = []
    async for each in User.objects.select_related().prefetch_related("groups", "user_permissions").all():
        objs.append(each)
    first = objs[0]
    print(first)
    print(first.__dict__)
    return objs

```
If I change it like this, won't it work?
The schema generation by create_schema is successful, but the response as per schema is failing because the auto-generated schema contains ManyToMany fields.

There are relations called groups and user_permissions in django.contrib.auth.models.User.
These are ManyToMany fields, so they will not be prefetched unless explicitly specified in prefetch_related().

The following code in DjangoGetter of django-ninja's Schema performs synchronous DB access in an asynchronous function when retrieving manyToMany fields that have not been retrieved previously. This is probably why SynchronousOnlyOperation is occurring.
```python
def _convert_result(self, result: Any) -> Any:
    if isinstance(result, Manager):
        return list(result.all())
```

I am guessing that the problem is caused by incompatibility between pydantic and django async orm, rather than a problem on the django-ninja side.

**Comment by azataiot** [comment]
> ```python
> @router.get("/async/users", response={
>     200: List[UserSchema]
> })
> async def async_get_users(request):
>     objs = []
>     async for each in User.objects.select_related().prefetch_related("groups", "user_permissions").all():
>         objs.append(each)
>     first = objs[0]
>     print(first)
>     print(first.__dict__)
>     return objs
> ```
> 
> If I change it like this, won't it work? The schema generation by `create_schema()` is successful, but the response as per schema is failing because the auto-generated schema contains ManyToMany fields.
> 
> There are relations called `groups` and `user_permissions` in `django.contrib.auth.models.User`. These are ManyToMany fields, so they will not be prefetched unless explicitly specified in `prefetch_related()`.
> 
> The following code in `DjangoGetter` of django-ninja's Schema performs synchronous DB access in an asynchronous function when retrieving ToMany fields that have not been retrieved previously. This is probably why SynchronousOnlyOperation is occurring.
> 
> ```python
> def _convert_result(self, result: Any) -> Any:
>     if isinstance(result, Manager):
>         return list(result.all())
> ```
> 
> I am guessing that the problem is caused by incompatibility between pydantic and django async orm, rather than a problem on the django-ninja side.

This is not only a Django User problem, if you work with any model schema that has relationship, create_schema() dose not work. It works in sync mode, and you can test them with the repository code i provided above, it includes two Models except the builtin User model, such as One, Two. If you generate schema using create_schema(), they will also cause the same problem. 

I am also guessing this might be cause by 'pydantic' `from_orm()`

**Comment by azataiot** [comment]
@oystersuki as I mentioned above, this might be a `pydantic` problem, but i checked the test code for SQLModel, it also uses pydantic undderthehood and utilizes `from_orm` but it works with async code, so I am now getting stuck.

I tried to analyze and debug the source code of `django-ninja` but did not able to locate the exact problem.

**Comment by oystersuki** [comment]
@azataiot 

I have looked at your repository.

If I get the relation on the User side, as in the following code, the error did not occur.

Also, if you increase the deep of create_schema(), there is no problem if you increase the fields to be prefetched accordingly.

After all, if you use asynchronous query, if you get it in advance in from_orm() so as not to run synchronous query, I guess the error will not occur.

I am sorry if I have not solved your problem.
```python
# ninja_demo/async_endpoints / one.py
# Created by azat at 8.02.2023
from typing import List

from ninja import Router
from ninja_demo.models import One, Two, User
from ninja_demo.schemas.common import OneSchema, TwoSchema, OneSchemaDeep, TwoSchemaDeep
from ninja_demo.schemas.user import UserSchema, UserSchemaManually

router = Router()


# =========== Sync ===========
@router.get("/async/one", response={
    200: List[OneSchema],
})
async def async_get_one_all(request):
    hoge = OneSchema
    objs = []
    async for each in One.objects.all():
        objs.append(each)
    return objs


@router.get("/async/two", response={
    200: List[TwoSchema]
})
async def async_get_two_all(request):
    objs = []
    async for each in Two.objects.all():
        objs.append(each)
    return objs


@router.get("/async/one/deep", response={
    200: List[OneSchemaDeep]
})
async def async_get_one_deep_all(request):
    objs = []
    async for each in One.objects.select_related().prefetch_related("user__groups", "user__user_permissions").all():
        objs.append(each)
    return objs


@router.get("/async/two/deep", response={
    200: List[TwoSchemaDeep]
})
async def async_get_two_deep_all(request):
    objs = []
    async for each in Two.objects.select_related().all():
        objs.append(each)
    return objs


@router.get("/async/one/last", response={
    200: OneSchema
})
async def async_get_one_last(request):
    obj = await One.objects.alast()
    return obj


@router.get("/async/two/last", response={
    200: TwoSchema
})
async def async_get_two_last(request):
    obj = await Two.objects.alast()
    return obj


@router.get("/async/one/first/deep", response={
    200: OneSchemaDeep
})
async def async_get_one_first_deep(request):
    obj = await One.objects.select_related().prefetch_related("user__groups", "user__user_permissions").afirst()
    return obj


@router.get("/async/two/first/deep", response={
    200: TwoSchemaDeep
})
async def async_get_two_first_deep(request):
    obj = await Two.objects.select_related().afirst()
    return obj


@router.get("/async/users", response={
    200: List[UserSchema]
})
async def async_get_users(request):
    objs = []
    async for each in User.objects.select_related().prefetch_related("groups", "user_permissions").all():
        objs.append(each)
    first = objs[0]
    print(first)
    print(first.__dict__)
    return objs


@router.get("/async/users/manually", response={
    200: List[UserSchemaManually]
})
async def async_get_users_manually(request):
    objs = []
    async for each in User.objects.select_related().prefetch_related("groups", "user_permissions").all():
        objs.append(each)
    return objs

```

**Comment by azataiot** [comment]
@oystersuki thanks for your answer.
Yes you are right,it runs if you add `.prefetch_related()`, but it is not the solution I believe. 

Consider the sync code, we do not need to do that for django-ninja, cause django-ninja checks each Model and if there is relationship it is fetching data in advance. (this is more general and it should also work for the async scenario)

This is what i am thinking. 

Even it is a solution that for each Model we manually provide the prefetch parameters, but it seems this is not the best solution. 

I am just thinking, why it is working without adding or providing such extra parameters for sync and for async we have to everything particularly manually ?

**Comment by chrismaille** [comment]
Because django ORM is declarative. One command can need several database connections to fulfill - like `request.user.groups` for example - behind the hood, there is a db connection to get the user and another to get his permissions.

In a asyncronous world, every db connection must be awaited, even the hidden ones.

Lets talk about performance now. Normally, this is one of main reasons we switch to async mode. But if you need to make several calls to the database, like django does on sync mode in a hidden way, you're wasting time. This is specially true when query several records at once. 

So, the best approach for performance (even in sync mode) is to make just one trip to the database and get everything you need at once. That's why `select_related` and `prefetch_related` exists.

The trade-off for velocity in the async world is the adding of these extra parameters to the database queries. You're moving from a _declarative ORM_ to a _declarative Repository class_. Something like this:

```python
class UserRepository:
   
   async def get_user_by_id(pk: int):
       return await User.objects.select_related.prefetch_related("groups", "user_permissions").aget(pk=pk)
```
```python
@router.get("/users/{user_id}", response=UserOut)
async def retrieve_user(request, user_id: int):
    db = UserRepository()
    return await db.get_user_by_id(pk=user_id)
```

**Comment by azataiot** [comment]
@chrismaille Thanks for your reply. So I think in async mode, there is no way we can just reuse one 'universal' Repository for all our models and we must have to write different Repository for each database Model. 

And I also find that even I am using async as much as possible, it seems like there is no such improvement on speed,i am not sure about the reason yet, but is this the possible case ? should n't async increase the django speed ?

**Comment by vitalik** [comment]
@azataiot 

> should n't async increase the django speed ?

`async != faster`

in general async helps you to cut number of threads and processes that utilizes the same amount of requests

most likely you will not see any gain in speed if you just use one process/thread  that just queries few records from db

but it can significantly reduce cpu usage when you await a bit longer operations like waiting for responses for network/db or reading files 

as you can see from this syntetic test - just 2 async workers outperform 2x times 24 sync workers

<img width="606" alt="SCR-20230219-n7t" src="https://user-images.githubusercontent.com/95222/219955420-82546ec4-9f2d-4c82-99d1-e9f13089d9e4.png">


but the key heare is concurency and "slow" network operation - this is the example where difference between sync and async shines. But if you have just one worker that mainly do cpu job - you will not get any improvement

**Comment by azataiot** [comment]
> @azataiot
> 
> > should n't async increase the django speed ?
> 
> `async != faster`
> 
> in general async helps you to cut number of threads and processes that utilizes the same amount of requests
> 
> most likely you will not see any gain in speed if you just use one process/thread that just queries few records from db
> 
> but it can significantly reduce cpu usage when you await a bit longer operations like waiting for responses for network/db or reading files
> 
> as you can see from this syntetic test - just 2 async workers outperform 2x times 24 sync workers
> 
> <img alt="SCR-20230219-n7t" width="606" src="https://user-images.githubusercontent.com/95222/219955420-82546ec4-9f2d-4c82-99d1-e9f13089d9e4.png">
> 
> but the key heare is concurency and "slow" network operation (slow means that workers mainly waiting for network to answer) - this is the example where difference between sync and async shines. But if you have just one worker that mainly do cpu job - you will not get any improvement

Thanks, 
In such case I need to mix both sync/async in my code. I have requests that catch data from other APIs and where probably I should go with Async and test the speed differences.
