### ISSUE TITLE
What is the best way to reuse resolve methods?

### ISSUE THREAD

**Issue by iainmaitland88** [vitalik/django-ninja#726]
Please describe what you are trying to achieve
I'd like to define resolve functions in one place to avoid repeating myself multiple times

Please include code examples (like models code, schemes code, view function) to help understand the issue
```python
# Django models
class Tag(models.Model):
    text: models.CharField(max_length=140)


class Post(models.Model):
    tags: models.ManyToManyField(Tag)


class Email(models.Model):
    tags: models.ManyToManyField(Tag)


# Ninja schemas
class Post(Schema):
    id: int
    tags: List[str] | None = None

    @staticmethod
    def resolve_tags(obj):
        return [t.text for t in obj.tags.all()]


class Email(Schema):
    id: int
    tags: List[str] | None = None

    # how can I abstract this?
    @staticmethod
    def resolve_tags(obj):
        return [t.text for t in obj.tags.all()]
```

**Comment by baseplate-admin** [comment]
Maybe  a mixin?

**Comment by baseplate-admin** [comment]
```python
class SomeMixin:
    @staticmethod
    def resolve_tags(obj):
        return [t.text for t in obj.tags.all()]

class Post(Schema,SomeMixin):
    id: int
    tags: List[str] | None = None

class Email(Schema, SomeMixin):
    id: int
    tags: List[str] | None = None
```

**Comment by iainmaitland88** [comment]
Hey @baseplate-admin 🙂  So that was my first thought, too but I run in to the following error

```
Traceback (most recent call last):
  File "/workspace/.venv/lib/python3.10/site-packages/ninja/operation.py", line 100, in run
    return self._result_to_response(request, result, temporal_response)
  File "/workspace/.venv/lib/python3.10/site-packages/ninja/operation.py", line 196, in _result_to_response
    result = response_model.from_orm(resp_object).dict(
  File "/workspace/.venv/lib/python3.10/site-packages/ninja/schema.py", line 164, in from_orm
    return super().from_orm(obj)
  File "/workspace/.venv/lib/python3.10/site-packages/pydantic/main.py", line 574, in from_orm
    raise validation_error
pydantic.error_wrappers.ValidationError: 7 validation errors for NinjaResponseSchema
response -> 0 -> tags -> 0
  str type expected (type=type_error.str)
response -> 1 -> tags -> 0
  str type expected (type=type_error.str)
response -> 1 -> tags -> 1
  str type expected (type=type_error.str)
response -> 8 -> tags -> 0
  str type expected (type=type_error.str)
response -> 8 -> tags -> 1
  str type expected (type=type_error.str)
response -> 8 -> tags -> 2
  str type expected (type=type_error.str)
response -> 8 -> tags -> 3
  str type expected (type=type_error.str)
```

However, I see that lifting the `tags` property in to a mixin like below it works just fine.

```python3
class TagMixin:
    tags: List[str] | None = None

    @staticmethod
    def resolve_tags(obj):
        return [t.text for t in obj.tags.all()]

class Post(Schema, TagMixin):
    id: int

class Email(Schema, TagMixin):
    id: int
```

I wonder why that is 🤔 I'll try and dig in a bit if I can find some time. Schemas are just an abstraction over Pydantic models afaik (I'm very new to Django Ninja) so maybe it's a limitation from Pydantic

**Comment by iainmaitland88** [comment]
So I think the problem is the way resolvers are registered. The constructor for [ResolverMetaclass](https://github.com/vitalik/django-ninja/blob/6ed724e24323647200f63593864c6074fc0827d5/ninja/schema.py#L127) finds any method that begins with `resolve_` and adds registers it for use later to "resolve" the field. The problem is that it only looks at the class passed in to it and not its parent classes.

My first thought was to simply make `Tag` subclass `Schema` but then Python frowns at us because we're trying to subclass the same type twice.

Perhaps if `Tag` subclassed a new type, something like `ResolverMixin`, we could look up the MRO for the current `Schema` class and also register `resolve_` methods from any `ResolverMixin` found along the way?

**Comment by iainmaitland88** [comment]
Below is an ugly hack to get this working using mixin type classes. Since [these lines](https://github.com/vitalik/django-ninja/blob/6ed724e24323647200f63593864c6074fc0827d5/ninja/schema.py#L130-L133) copy any existing `_ninja_resolver` from any of the base classes we can just provide our own.

```python
class TagResolver:
    @staticmethod
    def resolve_tags(obj):
        return [tag.text for tag in obj.tag.all()]

    _ninja_resolvers = {"tags": ninja.schema.Resolver(resolve_tags)}


class Post(Schema, TagResolver):
    tags: List[str] | None = None
```

This is obviously a terrible idea since we're relying on our understanding of the internals of how Ninja. However, what if Ninja provided a class that did this for us?

I'm also completely glossing over the obvious solution which is to define a function somewhere and use that inside the schema (like below) but that feels needlessly verbose.


```python
def _resolve_tags(obj):
    return [tag.text for tag in obj.tag.all()]


class Post(Schema):
    tags: List[str] | None = None

    @staticmethod
    def resolve_tags(obj):
        return _resolve_tags(obj)
```

**Comment by OtherBarry** [comment]
Would something like this work?

```python
class TagSchema(Schema):
    tags: List[str] | None = None

    @staticmethod
    def resolve_tags(obj):
        return [t.text for t in obj.tags.all()]


class Post(TagSchema):
    id: int
```

**Comment by iainmaitland88** [comment]
@OtherBarry for sure, that seems like it'd do the trick, too! That's more or less what I was thinking with `TagMixin` [here](https://github.com/vitalik/django-ninja/issues/726#issuecomment-1493415037) except it doesn't subclass `Schema` so I'm not actually sure that its resolver would be registered 🤔 My only complaint is that I'd prefer to keep the `tags` property in `Post` and simply provide a mixin class that defines the behaviour to resolve it.

**Comment by vitalik** [comment]
@iainmaitland88 

this should work the way you expect:

```Python
class TagsMixin(Schema):
    @staticmethod
    def resolve_tags(obj):
        return [t.text for t in obj.tags.all()]


class PostSchema(TagsMixin, Schema):
    id: int
    tags: list[str] = []
```
