### ISSUE TITLE
Can `ModelSchema` use django `IntegerRangeField`?

### ISSUE THREAD

**Issue by ohyunkyo** [vitalik/django-ninja#764]
*This is just simplified source code.

I try to use django `IntegerRangeField`. but when I get queryset with `ModelSchema`, `KeyError: 'IntegerRangeField'` has occurred. 

```
model.py

class MotorVehicle(BaseModel):
    ...
    price = IntegerRangeField(null=True, blank=True)
    ...
```

```
schema.py

class MotorVehicleOutSchema(ModelSchema):
    class Config:
        model = MotorVehicle
        model_exclude = ["id"]
```

```
api.py

@router.get("/motor-vehicles", response={200: List[MotorVehicleOutSchema]})
def get_motor_vehicles(request):

    motor_vehicles = MotorVehicle.objects.all()

    return motor_vehicles
```

```
error

Traceback (most recent call last):
  File "/Users/ohyunkyo/.pyenv/versions/3.11.1/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/ohyunkyo/.pyenv/versions/3.11.1/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ohyunkyo/.local/share/virtualenvs/oh-backend-v1-Vo_OQdRI/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/ohyunkyo/.local/share/virtualenvs/oh-backend-v1-Vo_OQdRI/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/Users/ohyunkyo/.local/share/virtualenvs/oh-backend-v1-Vo_OQdRI/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/Users/ohyunkyo/.local/share/virtualenvs/oh-backend-v1-Vo_OQdRI/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ohyunkyo/.local/share/virtualenvs/oh-backend-v1-Vo_OQdRI/lib/python3.11/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ohyunkyo/.local/share/virtualenvs/oh-backend-v1-Vo_OQdRI/lib/python3.11/site-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ohyunkyo/.local/share/virtualenvs/oh-backend-v1-Vo_OQdRI/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/ohyunkyo/.local/share/virtualenvs/oh-backend-v1-Vo_OQdRI/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/ohyunkyo/.local/share/virtualenvs/oh-backend-v1-Vo_OQdRI/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/ohyunkyo/.local/share/virtualenvs/oh-backend-v1-Vo_OQdRI/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ohyunkyo/.pyenv/versions/3.11.1/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/ohyunkyo/workdir/oh-backend-v1/server/urls.py", line 19, in <module>
    from .api import api, api_admin, api_iot, api_public
  File "/Users/ohyunkyo/workdir/oh-backend-v1/server/api.py", line 52, in <module>
    from common.api.motor_vehicle import router as motor_vehicle_router, admin_router as motor_vehicle_admin_router
  File "/Users/ohyunkyo/workdir/oh-backend-v1/common/api/motor_vehicle.py", line 22, in <module>
    from common.schema.motor_vehicle import MotorVehicleOutSchema, MotorVehicleInSchema
  File "/Users/ohyunkyo/workdir/oh-backend-v1/common/schema/motor_vehicle.py", line 15, in <module>
    class MotorVehicleOutSchema(ModelSchema):
  File "/Users/ohyunkyo/.local/share/virtualenvs/oh-backend-v1-Vo_OQdRI/lib/python3.11/site-packages/ninja/orm/metaclass.py", line 62, in __new__
    model_schema = create_schema(
                   ^^^^^^^^^^^^^^
  File "/Users/ohyunkyo/.local/share/virtualenvs/oh-backend-v1-Vo_OQdRI/lib/python3.11/site-packages/ninja/orm/factory.py", line 56, in create_schema
    python_type, field_info = get_schema_field(fld, depth=depth)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ohyunkyo/.local/share/virtualenvs/oh-backend-v1-Vo_OQdRI/lib/python3.11/site-packages/ninja/orm/fields.py", line 130, in get_schema_field
    python_type = TYPES[internal_type]
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'IntegerRangeField'
```

Can I use `IntegerRangeField` with `ModelSchema`?
If not, there's some different way in `django-ninja`?

**Comment by vitalik** [comment]
@ohyunkyo 

yeah, I guess it's makes sense to add all postgress specific fields (I think for now only arrayfield is there)

You can try for now the following:

before creating your schema:
```py
from ninja.orm.fields import TYPES

TYPES['IntegerRangeField'] = list[int]

class MotorVehicleOutSchema(ModelSchema):
   ...
```

**Comment by baseplate-admin** [comment]
>  postgress specific fields

Makes sense to me.. ( would you mind taking another peek at the ArrayField PR? )

**Comment by ohyunkyo** [comment]
@vitalik 
I decide not to use `IntegerRangeField` but should note my progress.

This code not occur error anymore. but a new error has presented:

```
from ninja.orm.fields import TYPES

TYPES['IntegerRangeField'] = list[int]

class MotorVehicleOutSchema(ModelSchema):
   ...
```

```
Traceback (most recent call last):
  File "/Users/ohyunkyo/.local/share/virtualenvs/oh-backend-v1-Vo_OQdRI/lib/python3.11/site-packages/ninja/operation.py", line 105, in run
    return self._result_to_response(request, result, temporal_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ohyunkyo/.local/share/virtualenvs/oh-backend-v1-Vo_OQdRI/lib/python3.11/site-packages/ninja/operation.py", line 202, in _result_to_response
    result = response_model.from_orm(resp_object).dict(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ohyunkyo/.local/share/virtualenvs/oh-backend-v1-Vo_OQdRI/lib/python3.11/site-packages/ninja/schema.py", line 164, in from_orm
    return super().from_orm(obj)
           ^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 579, in pydantic.main.BaseModel.from_orm
pydantic.error_wrappers.ValidationError: 100 validation errors for NinjaResponseSchema
response -> items -> 0 -> price
  value is not a valid list (type=type_error.list)
response -> items -> 1 -> price
  value is not a valid list (type=type_error.list)
response -> items -> 2 -> price
  value is not a valid list (type=type_error.list)
...
```

So, I try to change `price` but it wont work for me. 

```
class MotorVehicleOutSchema(ModelSchema):
    price: list[int]

    class Config:
        model = MotorVehicle
        model_exclude = EXCL_BASEMODEL_OUT
```

I found other way which does't use `IntegerRangeField` so I stop figure it out
May be later, when I use `IntegerRangeField` again will try this.

Thank you
