### ISSUE TITLE
How can I extend the paginate decorator?

### ISSUE THREAD

**Issue by dankgen-tobias** [vitalik/django-ninja#813]
I would like to extend the functionality of the paginate decorator. For example I would like to change the default or maximally allowed elements per page dynamically, without having to specify multiple subclasses of a pagination class. The desired result would be something like this:

```python
@my_paginate(default_items=10, max_items=50)
@router.get("items/")
@paginate
def get_items(request):
    return items
```
This should set the default value in the api to 10 and raise an error if a user tries to increase the `perPage` parameter to over 50.

So my idea was to extend the `@paginate` decorator. This example shows how (as to my knowledge) a decorator can be called inside another decorator:

```python
def add_hello(func):
    def wrapper_add_hello(*args, **kwargs):
        value = func(*args, **kwargs)
        value += " hello "
        return value
    return wrapper_add_hello


def add_hi_and_hello(func):
    def wrapper_add_hi_and_hello(*args, **kwargs):
        def wrapper_add_hello(*args, **kwargs):
            value = func(*args, **kwargs)
            value += " hi "
            return value
        return add_hello(wrapper_add_hello)(*args, **kwargs)
    return wrapper_add_hi_and_hello


@add_hi_and_hello
def name(n):
    return n

print(name("John"))

>>> "John hi  hello"
```

So to implement this for the paginate decorator, I thought I could do something like:

```python
def my_paginate(func):
    def wrapper_paginate(*args, **kwargs):       
        def wrapper_print(*args, **kwargs):
            print("Hello!")
            return func(*args, **kwargs)
        return pagination.paginate(pagination.PageNumberPagination)(wrapper_print)(*args, **kwargs)
    return wrapper_paginate
```

However, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/ninja/operation.py", line 104, in run
    result = self.view_func(request, **values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/site/api/pagination.py", line 57, in wrapper_add_hi
    return pagination.paginate(pagination.PageNumberPagination)(wrapper_add_hello)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ninja/pagination.py", line 136, in view_with_pagination
    pagination_params = kwargs.pop("ninja_pagination")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'ninja_pagination'
```

Looking into the codebase it seems like the `@paginate` decorator expects `paginator_params`:
```python
# ninja/pagination.py

def paginate(func_or_pgn_class: Any = NOT_SET, **paginator_params: Any) -> Callable:
    # code
```

So where does the decorator usually get this params from? The only other part of the code where the string `"ninja_pagination"` is used is here:

```python
#ninja/pagination.py -> _inject_pagination

view_with_pagination._ninja_contribute_args = [  # type: ignore
        (
            "ninja_pagination",
            paginator.Input,
            paginator.InputSource,
        ),
    ]
```
I tried to understand how the pagination works in detail and where the dictionary with this key actually comes from, but failed.

If there is a cleverer way to solve the problem I am of course grateful as well. However, I would also appreciate help/explanations for this particular question, since I am very interested how this decorator actually works :-)

**Comment by OtherBarry** [comment]
`paginator_params` are keyword argurments passed to the constructor of your paginator class.

So for your purpose, you could simply:

```python
MyPaginatorClass(BasePagination):
    class Input(Schema):
        page: int = Field(1, ge=1)
        perPage: Optional[int] = None

    def __init__(default_items: int = 10, max_items: int = 50, **kwargs):
        self.default_items = default_items
        self.max_items = max_items
        super().__init__(**kwargs)

    def paginate_queryset(
        self,
        queryset: QuerySet,
        pagination: Input,
        **params: Any,
    ) -> Any:
        if pagination.perPage = None:
            pagination.perPage = self.default_items
        if pagination.perPage > self.max_items:
            raise ValueError("page too big")
        offset = (pagination.page - 1) * self.pagination.perPage
        return {
            "items": queryset[offset : offset + self.pagination.perPage],
            "count": self._items_count(queryset),
        }
```
