### ISSUE TITLE
[BUG]  Weird Django ORM Behavior when using ModelSchema

### ISSUE THREAD

**Issue by nofalx** [vitalik/django-ninja#816]
**Describe the bug**

**Versions (please complete the following information):**
 - Python version: 3.11
 - Django version: 4.2
 - Django-Ninja version: 0.22.2
 - Pydantic version:1.10.9

I have a complicated application with 2 databases (postgres, postgres-timescaledb) that uses foreign key referencing each other. I have one view were I have a super complex query that suddenly stopped working once I added ModelSchema and refrenced one of the model im using. Once I have added the reference I started receiving this error when doing complex filters based on Q objects:

```
'str' object has no attribute '_meta'
```

Im not sure exactly what happens but below is the stacktrace, My suspicion is the ModelSchema somehow override internals of django manager or model. Please note that this view is a native django view and not a django ninja view.

Further more what I dont understand is that when i run django with `debugpy` module the error disappears. according to the stacktrace there is no `str` type where the error happens, so im not exactly sure what is happening here.

```
Environment:


Request Method: GET
Request URL: http://localhost:8080/en/maturity-index/

Django Version: 4.2.4
Python Version: 3.11.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django_celery_results',
 'corsheaders',
 'widget_tweaks',
 'allauth',
 'allauth.account',
 'django_otp',
 'django_otp.plugins.otp_totp',
 'user',
 'survey',
 'khadamati',
 'alert',
 'configuration',
 'common',
 'datalake',
 'debug_toolbar',
 'cms',
 'dashboard',
 'webpack_loader']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'common.middleware.PwaMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django_otp.middleware.OTPMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'app.logger.RequestLogMiddleware',
 'common.middleware.JsonHandlerMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']



Traceback (most recent call last):
  File "/home/ahmad/Downloads/github/service-observatory/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmad/Downloads/github/service-observatory/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmad/Downloads/github/service-observatory/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmad/Downloads/github/service-observatory/env/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmad/Downloads/github/service-observatory/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmad/Downloads/github/service-observatory/env/lib/python3.11/site-packages/django/views/generic/base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmad/Downloads/github/service-observatory/cms/views/maturity_index/view.py", line 61, in get_context_data
    context["data"] = self.get_maturity_data(
                      
  File "/home/ahmad/Downloads/github/service-observatory/cms/views/maturity_index/view.py", line 108, in get_maturity_data
    service_centers_integrated = centers_integrated_data(
                                 
  File "/home/ahmad/Downloads/github/service-observatory/cms/views/maturity_index/data.py", line 21, in centers_integrated_data
    active_objects = compiled_answers_qs.filter(
                     
  File "/home/ahmad/Downloads/github/service-observatory/env/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmad/Downloads/github/service-observatory/env/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmad/Downloads/github/service-observatory/env/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmad/Downloads/github/service-observatory/env/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmad/Downloads/github/service-observatory/env/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 
  File "/home/ahmad/Downloads/github/service-observatory/env/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1435, in build_filter
    value = self.resolve_lookup_value(value, can_reuse, allow_joins)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmad/Downloads/github/service-observatory/env/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1204, in resolve_lookup_value
    value = value.resolve_expression(
            
  File "/home/ahmad/Downloads/github/service-observatory/env/lib/python3.11/site-packages/django/db/models/query.py", line 1923, in resolve_expression
    query = self.query.resolve_expression(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmad/Downloads/github/service-observatory/env/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1163, in resolve_expression
    and table.join_field.related_model._meta.db_table != alias
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: AttributeError at /en/maturity-index/
Exception Value: 'str' object has no attribute '_meta'
```

![image](https://github.com/vitalik/django-ninja/assets/42375159/35b025f8-f875-47a7-bb26-d61367fc31d8)

**Comment by vitalik** [comment]
@nofalx well I do not see any 'ninja' in your stack trace, so pretty hard to tell what the issue is

my bet is that you trying to join 2 tables form different databases which is not allowed

**Comment by nofalx** [comment]
After investigating further turns out my models where not being imported correctly I discover the cause. My models are structure as below
```
app_a/models/__init__.py
app_a/models/file_a.py
app_a/models/file_a.py
```
My `app/models/__init__.py` was empty, after changing it to the below it worked
```
from .file_a import *
from .file_b import *
```

My apologies for opening issue as now it appears the issue is not related to ninja it was just a coincidence that an imported model that was used in ninja ModelScheme made the issue surface
