### ISSUE TITLE
ModelSchema  resolve field cause validation errors

### ISSUE THREAD

**Issue by shimachao** [vitalik/django-ninja#953]
python 3.11.6
django:4.2.7
django-ninja:1.0.1

```python
class MessageOut(ModelSchema):

    class Meta:
        model = Messages
        fields = ["id", "from_user_id", "to_user_id", "category",
                  "template_id", "template_name", "title", "image_url",
                  "view_url", "content", "is_read"]

    publish_time: int = Field(...,
                              gt=1700571683,
                              lt=6000000000,
                              title="发布时间",
                              description="unix 时间戳，秒级")

    @staticmethod
    def resolve_publish_time(msg: Messages) -> int:
        return int(msg.publish_time.timestamp())


class TasksResponse(Schema):
    messages: list[MessageOut] = Field(title="消息列表")
    total: int = Field(title="消息总数")
```

and the handle code 
```python
@api.get("messages", response=TasksResponse, summary="分页查询消息")
async def get_messages(request: ASGIRequest, task_in: Query[MessageFilter]):
    qs = Messages.objects.filter(is_deleted=False)
    if task_in.to_user_id > 0:
        qs = qs.filter(to_user_id=task_in.to_user_id)
    total = await qs.acount()
    offset = (task_in.page - 1) * task_in.page_size
    if offset > total:
        return TasksResponse(messages=[], total=total)

    qs = qs.order_by("-create_time", "-id")[offset: offset + task_in.page_size]
    return TasksResponse(messages=[msg async for msg in qs], total=total)
```

cause exception：
Traceback (most recent call last):
  File "/home/chao/message_center_django/env311/lib/python3.11/site-packages/ninja/operation.py", line 285, in run
    return self._result_to_response(request, result, temporal_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chao/message_center_django/env311/lib/python3.11/site-packages/ninja/operation.py", line 209, in _result_to_response
    validated_object = response_model.model_validate(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chao/message_center_django/env311/lib/python3.11/site-packages/pydantic/main.py", line 503, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 4 validation errors for NinjaResponseSchema
response.messages.0.publish_time
  Field required [type=missing, input_value=<ninja.schema.DjangoGette...bject at 0x7f7b89ddc8c0>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
response.messages.1.publish_time
  Field required [type=missing, input_value=<ninja.schema.DjangoGette...bject at 0x7f7b89e0b200>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
response.messages.2.publish_time
  Field required [type=missing, input_value=<ninja.schema.DjangoGette...bject at 0x7f7b89ddd180>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
response.messages.3.publish_time
  Field required [type=missing, input_value=<ninja.schema.DjangoGette...bject at 0x7f7b89e0b5c0>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing

**Comment by shimachao** [comment]
sorry, I fix it with:
```python
class MessageOut(ModelSchema):

    class Meta:
        model = Messages
        fields = ["id", "from_user_id", "to_user_id", "category",
                  "template_id", "template_name", "title", "image_url",
                  "view_url", "content", "is_read"]

    publish_time: int = Field(...,
                              gt=1700571683,
                              lt=6000000000,
                              title="发布时间",
                              description="unix 时间戳，秒级")

    @staticmethod
    def resolve_publish_time(msg: Messages) -> int:
        if isinstance(msg.publish_time, int):
            return msg.publish_time
        return int(msg.publish_time.timestamp())
```
