### ISSUE TITLE
[BUG] Issue migrating nested ModelSchema with Schema to ninja v1

### ISSUE THREAD

**Issue by mister-rao** [vitalik/django-ninja#963]
My schemas look like this:

``` python
class CatalogueDetailsOut(ModelSchema):
    author: AuthorStampOut = Field(..., alias="user")

    class Meta:
        model = Catalogue
        fields = "__all__"

class CuratedCatalogOut(ModelSchema):
    catalogues: list[CatalogueDetailsOut] = Field(...)

    class Meta:
        model = CuratedCatalog
        exclude = ["tags", "tagged_items"]

class ExploreOut(Schema):
    curated_catalogs: list[CuratedCatalogOut]
```

ExploreOut is my response schema for the API. 

But I get the following error:

``` python
12 validation errors for NinjaResponseSchema
response.curated_catalogs.0.catalogues.0.user.full_name
  Field required [type=missing, input_value=<ninja.schema.DjangoGette...bject at 0x7f1e84cc6f80>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
response.curated_catalogs.0.catalogues.0.user.username
  Field required [type=missing, input_value=<ninja.schema.DjangoGette...bject at 0x7f1e84cc6f80>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
response.curated_catalogs.0.catalogues.0.collection_id
  Field required [type=missing, input_value=<ninja.schema.DjangoGette...bject at 0x7f1e84cc4040>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
response.curated_catalogs.0.catalogues.0.user_id
  Field required [type=missing, input_value=<ninja.schema.DjangoGette...bject at 0x7f1e84cc4040>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
response.curated_catalogs.0.catalogues.1.user.full_name
  Field required [type=missing, input_value=<ninja.schema.DjangoGette...bject at 0x7f1e84cc6200>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
response.curated_catalogs.0.catalogues.1.user.username
  Field required [type=missing, input_value=<ninja.schema.DjangoGette...bject at 0x7f1e84cc6200>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
response.curated_catalogs.0.catalogues.1.collection_id
  Field required [type=missing, input_value=<ninja.schema.DjangoGette...bject at 0x7f1e84cc5b40>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
response.curated_catalogs.0.catalogues.1.user_id
  Field required [type=missing, input_value=<ninja.schema.DjangoGette...bject at 0x7f1e84cc5b40>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
response.curated_catalogs.0.catalogues.2.user.full_name
  Field required [type=missing, input_value=<ninja.schema.DjangoGette...bject at 0x7f1e84cc4100>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
response.curated_catalogs.0.catalogues.2.user.username
  Field required [type=missing, input_value=<ninja.schema.DjangoGette...bject at 0x7f1e84cc4100>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
response.curated_catalogs.0.catalogues.2.collection_id
  Field required [type=missing, input_value=<ninja.schema.DjangoGette...bject at 0x7f1e84cc7680>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
response.curated_catalogs.0.catalogues.2.user_id
  Field required [type=missing, input_value=<ninja.schema.DjangoGette...bject at 0x7f1e84cc7680>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing

```

Notice how there is collection_id for FK parsing, and user.field_name instead of author.field_name as specified in the field.

The code worked fine till **Ninja v0.22.2**

Won't be migrating to v1 unless this is fixed.

 - Python version: 3.11
 - Django version: 4.2.7
 - Django-Ninja version: 1.0.1
 - Pydantic version: 2.0

**Comment by vitalik** [comment]
@mister-rao could you also show `AuthorStampOut` ?

**Comment by vitalik** [comment]
@mister-rao tried to reproduce your case - but cannot:

models.py
```Python
from django.db import models


class Catalogue(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)


class CuratedCatalog(models.Model):
    name = models.CharField(max_length=100)
    catalogues = models.ManyToManyField(Catalogue)
    tags = models.CharField(max_length=100, blank=True)
    tagged_items = models.CharField(max_length=100, blank=True)

```

schemas.py
```Python
from ninja import Schema, Field, ModelSchema
from django.contrib.auth.models import User
from .models import Catalogue, CuratedCatalog


class AuthorStampOut(ModelSchema):
    full_name: str = Field(..., alias="get_full_name")

    class Meta:
        model = User
        fields = [
            "id",
            "username",
        ]


class CatalogueDetailsOut(ModelSchema):
    author: AuthorStampOut = Field(..., alias="user")

    class Meta:
        model = Catalogue
        fields = "__all__"


class CuratedCatalogOut(ModelSchema):
    catalogues: list[CatalogueDetailsOut] = Field(...)

    class Meta:
        model = CuratedCatalog
        exclude = ["tags", "tagged_items"]


class ExploreOut(Schema):
    curated_catalogs: list[CuratedCatalogOut]
````

api.py
```Python
from ninja import Router
from .models import CuratedCatalog
from .schemas import ExploreOut


router = Router()


@router.get("/explore", response=ExploreOut)
def explore(request):
    return {
        "curated_catalogs": CuratedCatalog.objects.all(),
    }

#....
api.add_router("", router)
```

result:

<img width="883" alt="SCR-20231128-kqol" src="https://github.com/vitalik/django-ninja/assets/95222/61abe362-bd44-4f74-9a59-16fce253a1cd">

**Comment by mister-rao** [comment]
that's odd. I'll try to migrate again to ninja v1 today and check it out. Will add a reproducible repo if the issue exists. One more thing, I'm using **ninja** along with **ninja-extra** to support class-based views.  However, I'll try it without class-based views too and update you with the findings. 

Thanks for the support! 🍻

**Comment by Bishwas-py** [comment]
I am also getting this issue:
```
1 validation error for LoginInline
  Input should be a valid dictionary or instance of LoginInline [type=model_type, input_value=<ninja.schema.DjangoGette...bject at 0x7fd225fd1300>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/model_type
Traceback (most recent call last):
  File "/path-to-project/venv/lib/python3.11/site-packages/ninja/operation.py", line 108, in run
    result = self.view_func(request, **values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path-to-project/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path-to-project/authentication/apis/auth_api.py", line 69, in login_user
    return 400, LoginInline(
                ^^^^^^^^^^^^
  File "/path-to-project/venv/lib/python3.11/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for LoginInline
  Input should be a valid dictionary or instance of LoginInline [type=model_type, input_value=<ninja.schema.DjangoGette...bject at 0x7fd225fd1300>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/model_type
Internal Server Error: /auth/login
[28/Nov/2023 19:12:12] "POST /auth/login HTTP/1.1" 500 1161
```

**Comment by Bishwas-py** [comment]
Fixed.

```python
class LoginInlineParam(Schema):
    username: str | list[str] | None = None
    password: str | list[str] | None = None
```

Weirdly this work on the previous version:

```python
class LoginInlineParam(Schema):
    username: str | list[str] = None
    password: str | list[str] = None
```

**Comment by mister-rao** [comment]
> ```python
> @router.get("/explore", response=ExploreOut)
> def explore(request):
>     return {
>         "curated_catalogs": CuratedCatalog.objects.all(),
>     }
> ```


I was trying it out again, returning a dictionary like this works.
```python
return {
    "curated_collections": curated_collections,
    "curated_catalogs": curated_catalogs,
    "curated_posts": curated_posts,
}
 
```

before (<v1.1.0) I was returning response like this which was working:

```python
return schemas.ExploreOut(
    curated_collections=[
        schemas.CuratedCollectionOut.from_orm(c) for c in curated_collections
    ],
    curated_catalogs=[
        schemas.CuratedCatalogOut.from_orm(c) for c in curated_catalogs
    ],
    curated_posts=[
        schemas.CuratedPostGroupOut.from_orm(g) for g in curated_posts
    ],
)

```

But anyways, returning dictionary is working now. Closing this issue.
