### ISSUE TITLE
[BUG] Serious issue with `alias` in v1 (django-ninja)

### ISSUE THREAD

**Issue by Bishwas-py** [vitalik/django-ninja#967]
While returning a prepared response from API, it gives an error (explained) saying the the alias field is missing.

**Code**
```python
class AuthOutSchema(Schema):
    is_authenticated: bool
    user_id: int = Field(..., alias="id")
    username: str
    redirect: str | None = None
```

```python
def login_user(request, data: LoginSchema):
    """
    If user is logged in successfully, login token will be returned in response headers.
    ```
    Set-Cookie: sessionid=<session_string>; expires=<time>; HttpOnly; Max-Age=<time>; Path=/; SameSite=Lax
    ```
    """
    user = get_user_model().objects.filter(username=data.username).first()

    if not user:
        return 400, LoginInline(
            inline={
                "username": "User with this username does not exist."
            }
        )

    if not user.check_password(data.password):
        return 400, LoginInline(
            inline={
                "password": "Password is incorrect."
            }
        )

    login(request, user)

    auth_out = AuthOutSchema.from_orm(user)
    auth_out.redirect = "/"
    return auth_out
```

**Error**
```shell
Traceback (most recent call last):
  File "/path-to-project/venv/lib/python3.11/site-packages/ninja/operation.py", line 109, in run
    return self._result_to_response(request, result, temporal_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path-to-project/venv/lib/python3.11/site-packages/ninja/operation.py", line 209, in _result_to_response
    validated_object = response_model.model_validate(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path-to-project/venv/lib/python3.11/site-packages/pydantic/main.py", line 503, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for NinjaResponseSchema
response.id
  Field required [type=missing, input_value=<ninja.schema.DjangoGette...bject at 0x7fccaa55f480>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
```

Now, when you return the data in this way, it works:
```python
...
    print("Prepping auth_out")
    auth_out = AuthOutSchema.from_orm(user)
    print("auth_out", auth_out.dict())

    auth_out.redirect = "/"
    new_auth_data = auth_out.dict()
    new_auth_data['id'] = new_auth_data.pop('user_id')

    print('new_auth_data', new_auth_data)
    return 200, new_auth_data
```

I believe it used to skip an already-created object (i.e. `auth_out`), but here it's redoing the process of preparing the data out of `auth_out`.

**Issue summary**
- Using a ninja schema, `AuthOutSchema` to model the expected fields of the response object.
- Encountering a pydantic validation error highlighting a missing "id" field.
- Able to bypass the error by manually replacing the `user_id` key with `id` in the output dictionary object.
- Noticing that Pydantic alias feature (`Field(..., alias="id")`) is not working as expected, potentially due to issues with how Ninja v1 handles alias in Schema.

Potential Causes:
- The error might be invoked when schema fields are validated against the prepared returned object of the AuthOutSchema.

**Versions (please complete the following information):**
 - Python version: 3.11
 - Django version: 4.2.6
 - Django-Ninja version: 1.0.1
 - Pydantic version: 2.5.2

**Comment by Bishwas-py** [comment]
Adding a print statement resolve cleared it out that the issue is schema object being rechecked:
```
    @staticmethod
    def resolve_user_id(user, context):
        print("resolve_user_id: ", "  user: ", user, "  context: ", context)
        return user.id
```

```
resolve_user_id:    user:  codie   context:  None
resolve_user_id:    user:  is_authenticated=True user_id=3 username='codie' redirect='/'   context:  {'request': <WSGIRequest: POST '/auth/login'>, 'response_status': 200}
```

**Comment by vitalik** [comment]
@Bishwas-py you did not show a`response` definition

```Python
@api.post(???? response=????) #
def login_user(request, data: LoginSchema):
   ...
```

but a  general issue with your code is you probably doing double validation/serialization - you can just return user object and it will be automatically validated and serialized:

```Python

class AuthOutSchema(Schema):
    is_authenticated: bool
    user_id: int = Field(..., alias="id")
    username: str
    redirect: str | None = None

@api.post("/login", response=AuthOutSchema)
def login_user(request, data: LoginSchema):
    # ...
    login(request, user)
    user.redirect = "/" # <---- do not do from_orm - just output user
    return user  # <----


```

**Comment by Bishwas-py** [comment]
Yes, I have a response definition (it is a working code from previous version):
```python
@router.post("/login", response={200: AuthOutSchema, 400: LoginInline}, auth=None,
             summary="Login user", openapi_extra=openapi_extra.auth_in_extra)
@csrf_exempt
def login_user(request, data: LoginSchema):
```

And `user` doesn't have a redirect attribute, even though we can assign them. Can't we do it in the schema object way in the version?

**Comment by Bishwas-py** [comment]
Thanks @vitalik , but the issue lies on:
```
from generics.schemas import MessageOut
from writer.abstract_models import ContentGenericModel
from writer.models import Keyword
from writer.schemas import UpdateContentSchema


def update_content(request, content: ContentGenericModel, data: UpdateContentSchema) -> tuple[int, MessageOut] | ContentGenericModel:
    if content.user != request.user:
        return 401, MessageOut(
            message="You are not authorized to update this page.",
            message_type="error",
            alias="unauthorized"
        )
    content.title = data.title
    content.meta_description = data.meta_description
    content.html_text = data.html_text

    sub_keywords = []
    for keyword_name in data.sub_keywords:
        keyword, _ = Keyword.objects.get_or_create(name=keyword_name)
        sub_keywords.append(keyword)

    content.sub_keywords.set(sub_keywords)
    content.save()

    return content

@router.put('/update/{content_uuid}', response={200: ContentSchema, 400: MessageOut, 404: MessageOut})
def update_page(request, content_uuid: str, data: UpdateContentSchema):
    """
    Update content detail
    """
    try:
        content = Content.objects.get(uuid=content_uuid)
        return update_content(request, content, data)
    except Content.DoesNotExist:
        return 404, {
            "message": "The content you are trying to update does not exist.",
            "message_type": "error",
            "alias": "content_not_found"
        }
```

What do you recommend in such situations? `update_content(...)` returns a tuple of `404, MessageOut` or `content`. If I change the `tuple[int, MessageOut]` to `tuple[int, dict]`, it doesn't feel so right and 'typed'.

**Comment by vitalik** [comment]
I guess you problem is that you mix business logic inside update_content with http/api

I would suggest to look into [custom error handling in ninja ](https://django-ninja.dev/guides/errors/)


```Python


# 1 create custom exception class


class MessageOutError(Exception):
    def __init__(self, status_code: int, message: str, type: str, alias: alias):
        self.status_code = status_code
        self.message = message
        self.message_type = type
        self.alias = alias
        super().__init__(status_code, message, type, alias)


# 2) register it in Ninja

@api.exception_handler(MessageOutError)
def service_unavailable(request, exc):
    return api.create_response(
        request,
        {"message": exc.message, "alias": exc.alias, "message_type": exc.message_type},
        status=exc.status_code,
    )

# 3 use it:

def update_content(request, content: ContentGenericModel, data: UpdateContentSchema) -> ContentGenericModel:
    if content.user != request.user:
        raise MessageOutError(
            401,
            message="You are not authorized to update this page.",
            message_type="error",
            alias="unauthorized"
        )
       ...



@router.put('/update/{content_uuid}', response={200: ContentSchema, 400: MessageOut, 404: MessageOut})
def update_page(request, content_uuid: str, data: UpdateContentSchema):
    try:
        content = Content.objects.get(uuid=content_uuid)
        return update_content(request, content, data)
    except Content.DoesNotExist:
        raise MessageOutError(
             404,
            "message": "The content you are trying to update does not exist.",
            "message_type": "error",
            "alias": "content_not_found"
        }


```

**Comment by Bishwas-py** [comment]
That's really smart, master. I already have an `MessageValueError` exception, for field validation purposes. I guess, I'll use that with it. I guess, I'll use that here also, as you mentioned. I dunno why, I wasn't able to think like that. Thanks a lot for response and thanks a lot for `django-ninja`.

2 months ago, I was in a voyage of create [djapy](https://github.com/Bishwas-py/djapy), during it's development, I came to know about `django-ninja`, now I am confused if I should continue it or not. Thanks again.

![image](https://github.com/vitalik/django-ninja/assets/42182303/e37e3896-cb01-4f56-9aea-fbf754207b4d)

![image](https://github.com/vitalik/django-ninja/assets/42182303/fb4b57aa-4b4f-47ea-a9a6-9e7c1809ec6d)
