### ISSUE TITLE
[BUG] When running the server using django-ninja's router, there is an issue of multiple objects with different types being received.

### ISSUE THREAD

**Issue by Gibartes** [vitalik/django-ninja#973]
**Describe the bug**

**Versions (please complete the following information):**
 - Python version: 3.11
 - Django version: 4.2.7
 - Django-Ninja version: 1.0.1
 - Pydantic version: 2.5.2

Hello, developers!

When trying to set up a new project with django-ninja, the following error occurred. Please check if this is a bug or fault.
The bug exists at line 385, and this line belongs to the 'add_router' method.

self._routers.extend(router.build_routers(prefix))
router.set_api_instance(self, parent_router)

The old version of django-ninja - 0.22.2, it seems to work without any issues.

![old_version](https://github.com/vitalik/django-ninja/assets/29702789/6533d9dd-7530-4f2e-af21-f71d5302b110)

But the newest version 1.0.1,

![image](https://github.com/vitalik/django-ninja/assets/29702789/9005528b-f92c-4bd8-927f-771f20b05992)
![image](https://github.com/vitalik/django-ninja/assets/29702789/304c6549-d0b1-4d13-8692-d5b714b75f88)

The "Router" class object and the "NinjaAPI" class object seem to be mixed up, and when checked with the getattr function, the NinjaAPI does not have the "build_routers" method. There appears to be a bug or fault in the code.

Was it originally intended for Python objects of different types to cross over like this?

**Comment by Gibartes** [comment]
I have confirmed that it should operate like the previous version.

The text version of the error message is as follows.
--------------------------------------------------------

test_attr:  <bound method Router.build_routers of <ninja.router.Router object at 0x7f5c92b62390>>
type:  <class 'ninja.router.Router'>
test_attr:  False
type:  <class 'ninja.main.NinjaAPI'>
test_attr:  <bound method Router.build_routers of <ninja.router.Router object at 0x7f5c92bcd510>>
type:  <class 'ninja.router.Router'>
test_attr:  False
type:  <class 'ninja.main.NinjaAPI'>
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dev/slp/env/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/dev/slp/env/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/home/dev/slp/env/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/dev/slp/env/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/slp/env/lib/python3.11/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/slp/env/lib/python3.11/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/home/dev/slp/env/lib/python3.11/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/home/dev/slp/env/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/dev/slp/env/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/dev/slp/env/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/dev/slp/env/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dev/slp/hassm/hassm/urls.py", line 25, in <module>
    proc_mon_v1.add_router('/v1', proc_mon_v1)
  File "/home/dev/slp/env/lib/python3.11/site-packages/ninja/main.py", line 387, in add_router
    self._routers.extend(router.build_routers(prefix))
                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NinjaAPI' object has no attribute 'build_routers'


----------
Thank you for your efforts.
