### ISSUE TITLE
[BUG] GenericModel error " Input should be a valid dictionary or instance of xxx""

### ISSUE THREAD

**Issue by amzar96** [vitalik/django-ninja#979]
**Describe the bug**
My objective is to get the generic response schema for all the requests.

schemas.py
```python
class ErrorMsg(BaseModel):
    message: Optional[str] = None
    success: bool = True

GenericResultsType = TypeVar("GenericResultsType")

class StdResponse(ErrorMsg, GenericModel, Generic[GenericResultsType]):
    data: GenericResultsType

class ListStdResponse(ErrorMsg, GenericModel, Generic[GenericResultsType]):
    data: List[GenericResultsType]
```

views.py
```python
@router.get(
    "/users/{user_id}",
    response=StdResponse[Union[UserSchema, None]],
)
def get_user(request, user_id: int):
    user = model.User.objects.filter(id=user_id).first()

    if user:
        return StdResponse(data=user)
    else:
        return StdResponse(data=None)
```

*error*
```bash
response
  Input should be a valid dictionary or instance of StdResponse[Union[UserSchema, NoneType]] [type=model_type, input_value=StdResponse(message=None,...rue, data=<User: amzar>), input_type=StdResponse]
    For further information visit https://errors.pydantic.dev/2.5/v/model_type
Traceback (most recent call last):
  File "/Users/amzar/Documents/python_env/ty/lib/python3.11/site-packages/ninja/operation.py", line 109, in run
    return self._result_to_response(request, result, temporal_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amzar/Documents/python_env/ty/lib/python3.11/site-packages/ninja/operation.py", line 209, in _result_to_response
    validated_object = response_model.model_validate(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amzar/Documents/python_env/ty/lib/python3.11/site-packages/pydantic/main.py", line 503, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for NinjaResponseSchema
response
  Input should be a valid dictionary or instance of StdResponse[Union[UserSchema, NoneType]] [type=model_type, input_value=StdResponse(message=None,...rue, data=<User: amzar>), input_type=StdResponse]
    For further information visit https://errors.pydantic.dev/2.5/v/model_type
```

**Versions (please complete the following information):**
 - Python version: 3.11.6
 - Django version: 4.2.7
 - Django-Ninja version: 1.0.1
 - Pydantic version: 2.5.2

Note you can quickly get this by runninng in `./manage.py shell` this line:
```bash
>>> import django; import pydantic; import ninja; django.__version__; ninja.__version__; pydantic.__version__
'4.2.7'
'1.0.1'
'2.5.2'
```

**Comment by vitalik** [comment]
@amzar96 I"m not sure what's you `GenericModel`...

but overal I think pydantic wants you to set actual generic type when creating an object (so that it matches the response)

this will work - but kinda ugly:
```Python
def get_user(request, user_id: int):
    user = User.objects.filter(id=user_id).first()

    if user:
        return StdResponse[Union[UserSchema, None]](data=user)
    else:
        return StdResponse[Union[UserSchema, None]](data=None)
```

you probably need to make type aslias to make it nicer

```
UserReponse = StdResponse[Union[UserSchema, None]]
```
and then use it


Also keep in mind that django-ninja will validate and serialize objects autmatically even if they not an acutally type of response model - so you can just return dicts:

```Python
```

**Comment by vitalik** [comment]
> 1. How to use `UserReponse` in the router API? It seems good, but I need to try it first.
> 2. If I return `dict`, does it mean no need to set the `response` in the router decorator?
> 
> I'm newbie to Ninja API and Pydantic 🙏 and want to learn best practice create API.
> 
> Thank you @vitalik .

well I think your vision is a bit different from intended

basically the whole idea - you need to return some json-compatible data or querysets

then what you defined in `response=` will be used to validate your response and serialize it to JSON

so the advisable way is return dict (and set response= as it is required to document your api and serialise)

basically this is a go to code:

```Python
@router.get(
    "/users/{user_id}",
    response=StdResponse[Union[UserSchema, None]],
)
def get_user(request, user_id: int):
    user = User.objects.filter(id=user_id).first()

    if user:
        return {'data': user}
    else:
        return {'data': None}
```

or even smaller - because .first returns a None:

```Python
```

**Comment by amzar96** [comment]
Great! Able to populate the output now using `return {'data': user}`
Thanks @vitalik

**Comment by shepherd1530** [comment]
If you are using pydantic v2, the below should help you.

```py
class ErrorMsg(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    message: Optional[str] = None
    success: bool = True
    
    
# You should be able to return
@router.get(
    "/users/{user_id}",
    response=StdResponse[Union[UserSchema, None]],
)
def get_user(request, user_id: int):
    user = model.User.objects.filter(id=user_id).first()

    return StdResponse(data=user)
```
